<?php
	$mod_lang_output = array_merge($lang_output,
			array(
			
			//General
			'MODULE_NAME'						=>	'File Manager',
			'MODULE_DESCR'						=>	'File manager module',
			'MODULE_ICON'						=>	'<i class=\'fa fa-file icon_info icon_color\'></i>',
			'FORM_BUTTON_UPDATE'				=>	'Update',
			'FORM_HELP_LEAVE_EMPTY'				=>	'Leave blank if same',
			'FORM_HELP_CRT_MAX'					=>	'Max Char.',
			'FORM_LABEL_LANGUAGE'				=>	'Language',
			'FORM_LABEL_SEX'					=>	'Sex',
			'FORM_VALUE_CHOOSE'					=> 	'Choose',
			'FORM_VALUE_SEX_1'					=>	'Male',
			'FORM_VALUE_SEX_2'					=>	'Female',
			
			//Admin --	Tables
			'TABLE_HEADER_TITLE' 				=> 	'Title',
			'TABLE_HEADER_AUTHOR' 				=> 	'Author',
			'TABLE_HEADER_DATE-CREA'			=> 	'Date created',
			'TABLE_HEADER_DATE-START'			=> 	'Start',
			'TABLE_HEADER_DATE-END'				=> 	'End',
			'TABLE_HEADER_ACTION'				=> 	'Actions',
			'TABLE_HEADER_CATEGORY'				=>	'Category',
			'TABLE_HEADER_AUTHOR_GROUP'			=>	'Group',
			'TABLE_HEADER_DESCRIPTION'			=>	'Description',
			
			//Admin -- Forms
			'FORM_LABEL_CATEGORY'				=>	'Category',
			'FORM_LABEL_FILE_CATEGORY'			=>	'Category',
			'FORM_LABEL_CODE'					=>	'Code',
			'FORM_LABEL_TITLE'					=>	'Title',
			'FORM_LABEL_FILE_AUTHOR'			=>	'Author',
			'FORM_LABEL_HEADER'					=>	'Header',
			'FORM_LABEL_FILE_HEADER'			=>	'Header',
			'FORM_LABEL_FILE_TAGS'				=>	'Key words',
			'FORM_LABEL_FILE_CONTENT'			=>	'Main content',
			'FORM_LABEL_FILE_TITLE'				=>	'Title',
			'FORM_LABEL_LABEL'					=>	'Label',
			'FORM_LABEL_DATE-PUB'				=>	'Publication date',
			'FORM_LABEL_DATE-CREA'				=>	'Creation date',
			'FORM_LABEL_FILE_THUMBNAIL'			=>	'Thumbnail',
			'FORM_LABEL_FIRST-NAME'				=>	'First name',
			'FORM_LABEL_LAST-NAME'				=>	'Last name',
			'FORM_LABEL_GROUP'					=>	'Group',
			'FORM_LABEL_AUTHOR_GROUP'			=>	'Authors group',
			'FORM_LABEL_DESCRIPTION'			=>	'Description',
			'FORM_LABEL_FILE_IMG_HEADER'		=>	'Header image',
			'FORM_LABEL_ADD_FILE'				=>	'Insert a file',
			'FORM_BUTTON_ADD_FILE'				=>	'Insert file',
			'FORM_BUTTON_ADD_FILE_AUTHOR'		=>	'Insert an author',
			'FORM_BUTTON_ADD_CATEGORY'			=>	'Insert category',
			'FORM_BUTTON_ADD_AUTHOR_GROUP'		=>	'Insert author\'s group',
			'FORM_BUTTON_UPDATE_AUTHOR_GROUP'	=>	'Update author\'s group',
			'FORM_BUTTON_UPDATE_FILE'			=>	'Update file',
			
			//Admin -- Headers
			'PAGE_HEADER_ADD_FILE'				=>	'Insert a file',
			'PAGE_HEADER_ADD_FILE_CATEGORY'		=>	'Insert category',
			'PAGE_HEADER_ADD_AUTHOR_GROUP'		=>	'Insert authors group',
			'PAGE_HEADER_ADD_FILE_AUTHOR'		=>	'Insert author',
			'PAGE_HEADER_UPDATE_AUTHORS_GROUP'	=>	'Update authors group',
			'PAGE_HEADER_UPDATE_FILE'			=>	'Update a file',
			'PAGE_HEADER_UPDATE_FILE_CATEGORY'	=>	'Update a file category',
			'PAGE_HEADER_UPDATE_FILE_AUTHOR'	=>	'Update author',
			'PAGE_HEADER_LIST_FILES'			=>	'List files',
			'PAGE_HEADER_LIST_FILE_CATEGORIES'	=>	'List categories',
			'PAGE_HEADER_LIST_FILE_COMMENTS'	=>	'List comments',
			'PAGE_HEADER_LIST_FILE_AUTHORS'		=>	'List authors',
			'PAGE_HEADER_LIST_AUTHOR_GROUPS'	=>	'List authors groups',
	
			'PAGE_LINK_ADD_FILE_AUTHOR_GROUP'	=>	'Insert authors group',
			'PAGE_LINK_ADD_FILE_AUTHOR'			=>	'Insert author',
					
			//Admin --	Validations
			'FILE_MANDATORY_ERROR'				=>	'Error!<br />You should fill <strong>all</strong> mandatory fields please...',
			'FILE_EXT_ERROR'					=>	'Sorry!<br />You should choose a file with the autorized extension',
			'FILE_EXISTS_ERROR'					=>	'Sorry!<br />This title exists already.<br />Please choose another one...',
			'FILE_DESCR_EXISTS_ERROR'			=>	'Sorry!<br />That description has been used for another file already.<br />',
			'FILE_EMPTY_ERROR'					=>	'Error!<br />You should specify a file to be downloaded.',
			'FILE_INSERT_SUCCESS'				=>	'Congratulations<br />A file has been successfully uploaded on the server.',
			'FILE_UPDATE_SUCCESS'				=>	'Congratulations!<br />File successfully updated.',
			'FILE_REPLACE_UPDATE_SUCCESS'		=>	'Congratulations<br />A file has been successfully replaced and updated.',
			'FILE_CAT_CODE_MANDATORY_ERROR'		=>	'Error<br />The code is mandatory.',
			'FILE_CAT_EMPTY_ERROR'				=>	'Sorry!<br />You must specify a category please.',
			'FILE_CAT_CODE_EXISTS_ERROR'		=>	'Sorry!<br />The code is already attributed<br />Please try with another one.',
			'FILE_CAT_EXISTS_ERROR'				=>	'Sorry!<br />The category exists already.<br />Please try with another category value.',
			'FILE_CAT_INSERT_SUCCESS'			=>	'Congatulations!<br />Category succesfully created.',
			'FILE_CAT_CODE_UPDATE_ERROR'		=>	'Error!<br />Unable to update the category because of a mistake on the category code.',
			'FILE_CAT_UPDATE_SUCCESS'			=>	'Congratulations!<br />Category successfully updated.',
			'FILE_DELETE_SUCCESS'				=>	'Congratulations!<br />File '.$fileId.' sucessfully deleted.',
			'FILE_HIDDEN_SUCCESS'				=>	'Congratulations!<br />Now the file is set invisible to the visitors of the website.',
			'FILE_VISIBLE_SUCCESS'				=>	'Congratulations!<br />You have allowed the file to be visible in the website.',
			'FILE_CAT_DELETE_SUCCESS'			=>	'Congratulations!<br />File category successfully deleted.',
			'FILE_CAT_VISIBLE_SUCCESS'			=>	'Congratulations!<br />File category is now visible for the visitors of the website.',
			'FILE_CAT_HIDDEN_SUCCESS'			=>	'Congratulations!<br />The file category is now hidden for the visitors of the website.',
            "FILE_ERROR_CHOOSE"					=>	"Please choos a file from your device",
			"FILE_CFRM_SENT"					=>	"File successfuly loaded!",
			"FILE_ERROR_CANT_SEND"				=>	"Sorry!<br />Unable to load your file",
			"FILE_CLICK_PREVIEW"				=>	"Click here to preview your file content",
			"FILE_BTN_UPLOAD"					=>	"Download the file",
			"FILE_NOT_ALLOWED"					=>	"is not an authorized file type",
			"FILE_LBL_IMPORT"					=>	"File import form",
			"FILE_LBL_DESCR"					=>	"(NB : CSV or VCF only)",
			"FILE_LBL_PLACEH"					=>	"Your contact file",

			//Admin menu
			"FILE_ADMIN_MENU_DISPLAY"			=>	"Display files",
			"FILE_ADMIN_MENU_CREATE"			=>	"Add a file",
			"FILE_ADMIN_MENU_CAT_DISPLAY"		=>	"Show categories",
			"FILE_ADMIN_MENU_CAT_CREATE"		=>	"Add category",
			

			//Main page display
			'FILE_HOME_BOX_ACCORDION'			=>	'Library',
			"FILE_SIDE_BOX_TITLE" 				=> 	"Files",
			"FILE_BOX_TITLE" 					=> 	"Top files",
			"FILE_BOX_LINK"						=> 	"&raquo;Go to library",
			"FILE_BOX_LINK_ALL"					=> 	"See all files",
			"FILE_PAGE_TITLE"					=> 	"Downloading area",
			"FILE_PAGE_HEADER"					=> 	"North-West Region :: Library",
			"FILE_PAGE_CAT_HEADER"				=> 	"North-West Region :: Files by category",
			"FILE_PAGE_BACK"					=> 	"Back to the library",
			"FILE_PJ"							=> 	"Attachment",
			"FILE_CAT_SIDE_BOX_TITLE"			=>	"Categories",
			"FILE_LOCATION"						=>	"Location",
			"NO_FILE"							=>	"No file to be displayed",
			"FILE_LBL_FILE"						=> 	"File",
			"FILE_LBL_WIDTH"					=>	"Size",
			"FILE_LBL_DLD"						=>	"Download",
			"FILE_LBL_MORE"						=>	"&raquo; More",
			"FILE_CAT_ERR"						=>	"No category",
			"FILE_LBL_DETAIL_DESCR"             =>  "About this file",
            "FILE_LBL_TYPE"                     =>  "File type",
            "FILE_LBL_SIZE"                     =>  "File size"
			)
	);