<?php
	$mod_lang_output = array_merge($lang_output,
			array(
			
			//General
			'MODULE_NAME'						=>	'File Manager',
			'MODULE_DESCR'						=>	'Gestionnaire des fichiers',
			'MODULE_ICON'						=>	'<i class=\'fa fa-file icon_info icon_color\'></i>',
			'FORM_BUTTON_UPDATE'				=>	'Mettre &agrave; jour',
			'FORM_HELP_LEAVE_EMPTY'				=>	'Laisser vide si identique',
			'FORM_HELP_CRT_MAX'					=>	'Caract&egrave;res max.',
			'FORM_LABEL_LANGUAGE'				=>	'Langue',
			'FORM_LABEL_SEX'					=>	'Sexe',
			'FORM_VALUE_CHOOSE'					=> 	'Choisir',
			'FORM_VALUE_SEX_1'					=>	'Masculin',
			'FORM_VALUE_SEX_2'					=>	'Feminin',
			
			//Admin	--	Tables
			'TABLE_HEADER_TITLE' 				=> 	'Titre',
			'TABLE_HEADER_AUTHOR' 				=> 	'Auteur',
			'TABLE_HEADER_DATE-CREA'			=> 	'Cr&eacute;&eacute; le',
			'TABLE_HEADER_DATE-START'			=> 	'D&eacute;but',
			'TABLE_HEADER_DATE-END'				=> 	'Fin',
			'TABLE_HEADER_ACTION'				=> 	'Actions',
			'TABLE_HEADER_CATEGORY'				=>	'Cat&eacute;gorie',
			'TABLE_HEADER_AUTHOR_GROUP'			=>	'Groupe',
			'TABLE_HEADER_DESCRIPTION'			=>	'Description',
			
			//Admin --	Forms
			'FORM_LABEL_CATEGORY'				=>	'Cat&eacute;gorie',
			'FORM_LABEL_FILE_CATEGORY'			=>	'Rubrique',
			'FORM_LABEL_CODE'					=>	'Code',
			'FORM_LABEL_TITLE'					=>	'Titre',
			'FORM_LABEL_FILE_AUTHOR'			=>	'Auteur',
			'FORM_LABEL_HEADER'					=>	'Chapeau',
			'FORM_LABEL_FILE_HEADER'			=>	'Chapeau',
			'FORM_LABEL_FILE_TAGS'				=>	'Mots-cl&eacute;s',
			'FORM_LABEL_FILE_CONTENT'			=>	'Contenu principal',
			'FORM_LABEL_FILE_TITLE'				=>	'Titre',
			'FORM_LABEL_LABEL'					=>	'Libell&eacute;',
			'FORM_LABEL_DATE-PUB'				=>	'Date de publication',
			'FORM_LABEL_DATE-CREA'				=>	'Date de cr&eacute;ation',
			'FORM_LABEL_FILE_THUMBNAIL'			=>	'Imagette',
			'FORM_LABEL_FIRST-NAME'				=>	'Pr&eacute;nom',
			'FORM_LABEL_LAST-NAME'				=>	'Nom',
			'FORM_LABEL_GROUP'					=>	'Groupe',
			'FORM_LABEL_AUTHOR_GROUP'			=>	'Groupe d\'auteurs',
			'FORM_LABEL_DESCRIPTION'			=>	'Description',
			'FORM_LABEL_FILE_IMG_HEADER'		=>	'Image d\'ent&ecirc;te',
			'FORM_LABEL_ADD_FILE'				=>	'Ajouter un fichier',
			'FORM_BUTTON_ADD_FILE'				=>	'Ajouter un fichier',
			'FORM_BUTTON_ADD_FILE_AUTHOR'		=>	'Ajouter un auteur',
			'FORM_BUTTON_ADD_CATEGORY'			=>	'Ajouter la cat&eacute;gorie',
			'FORM_BUTTON_ADD_AUTHOR_GROUP'		=>	'Ajouter un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_AUTHOR_GROUP'	=>	'Modifier un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_FILE'			=>	'Modifier le fichier',
			
			//Admin -- 	Headers
			'PAGE_HEADER_ADD_FILE'				=>	'Ajouter un fichier',
			'PAGE_HEADER_ADD_FILE_CATEGORY'		=>	'Ajouter une cat&eacute;gorie de fichier',
			'PAGE_HEADER_ADD_AUTHOR_GROUP'		=>	'Ajouter un groupe d\'auteur',
			'PAGE_HEADER_ADD_FILE_AUTHOR'		=>	'Ajouter un auteur',
			'PAGE_HEADER_UPDATE_AUTHORS_GROUP'	=>	'Modifier un groupe d\'auteurs',
			'PAGE_HEADER_UPDATE_FILE'			=>	'Modifier le fichier',
			'PAGE_HEADER_UPDATE_FILE_CATEGORY'	=>	'Modifier une cat&eacute;gorie de fichier',
			'PAGE_HEADER_UPDATE_FILE_AUTHOR'	=>	'Modifier un auteur',
			'PAGE_HEADER_LIST_FILES'			=>	'Afficher les fichiers',
			'PAGE_HEADER_LIST_FILE_CATEGORIES'	=>	'Afficher les cat&eacute;gories',
			'PAGE_HEADER_LIST_FILE_COMMENTS'	=>	'Afficher les commentaires',
			'PAGE_HEADER_LIST_FILE_AUTHORS'		=>	'Afficher les auteurs',
			'PAGE_HEADER_LIST_AUTHOR_GROUPS'	=>	'Afficher les groupes d\'auteurs',
	
			'PAGE_LINK_ADD_FILE_AUTHOR_GROUP'	=>	'Ajouter un groupe d\'auteur',
			'PAGE_LINK_ADD_FILE_AUTHOR'			=>	'Ajouter un auteur',
					
			//Admin	-- 	Validations
			'FILE_MANDATORY_ERROR'				=>	'Erreur!<br />Vous devez remplir <strong>tous</strong> les champs obligatoires (*)...',
			'FILE_EXT_ERROR'					=>	'D&eacute;sol&eacute;!<br />Seuls les fichiers avec les extensions autoris&eacute;es sont accept&eacute;s',
			'FILE_EXISTS_ERROR'					=>	'D&eacute;sol&eacute;<br />Ce titre est d&eacute;j&agrave; attribu&eacute;.<br />Veuillez en choisir un autre svp...',
			'FILE_DESCR_EXISTS_ERROR'			=>	'D&eacute;sol&eacute;!<br />Cette description est d&eacute;j&agrave; utilis&eacute;e pour un autre fichier.',
			'FILE_EMPTY_ERROR'					=>	'Erreur!<br />Vous devez pr&eacute;sicer le fichier &agrave; t&eacute;l&eacute;charger.',
			'FILE_INSERT_SUCCESS'				=>	'Bravo<br />Un fichier a &eacute;t&eacute; charg&eacute; sur le serveur avec succ&egrave;s.',
			'FILE_UPDATE_SUCCESS'				=>	'Bravo!<br />Fichier mis &agrave; jour avec succ&egrave;s.',
			'FILE_REPLACE_UPDATE_SUCCESS'		=>	'Bravo<br />Un fichier a &eacute;t&eacute; remplac&eacute; et mis &agrave; jour avec succ&egrave;s.',
			'FILE_CAT_CODE_MANDATORY_ERROR'		=>	'Erreur<br />Le code est obligatoire.',
			'FILE_CAT_EMPTY_ERROR'				=>	'D&eacute;sol&eacute;!<br />Vous devez pr&eacute;ciser une cat&eacute;gorie svp.',
			'FILE_CAT_CODE_EXISTS_ERROR'		=>	'D&eacute;sol&eacute;!<br />Code d&eacute;j&agrave; attribu&eacute;.<br />Veuillew en essayer un autre.',
			'FILE_CAT_EXISTS_ERROR'				=>	'D&eacute;sol&eacute;!<br />Cat&eacute;gorie d&eacute;j&agrave; existante.<br />Veuillez en proposer une autre svp.',
			'FILE_CAT_INSERT_SUCCESS'			=>	'Bravo!<br />Cat&eacute;gorie cr&eacute;&eacute;e avec succes.',
			'FILE_CAT_CODE_UPDATE_ERROR'		=>	'Erreur!<br />Impossible de modifier la cat&eacute;gorie &agrave; caus d\'une erreur dans le code.',
			'FILE_CAT_UPDATE_SUCCESS'			=>	'Bravo!<br />Categorie mise &agrave; jour avec succ&egrave;s.',
			'FILE_DELETE_SUCCESS'				=>	'Bravo!<br />Fichier '.$fileId.' supprim&eacute; avec succ&egrave;s.',
			'FILE_HIDDEN_SUCCESS'				=>	'Bravo!<br />Le fichier est d&eacute;sormais masqu&eacute; pour les visiteurs du site web.',
			'FILE_VISIBLE_SUCCESS'				=>	'Bravo!<br />Le fichier est d&eacute;sormais visible pour les visiteurs du site web.',
			'FILE_CAT_DELETE_SUCCESS'			=>	'Bravo!<br />Cat&eacute;gorie supprim&eacute;e avec succ&egrave;s.',
			'FILE_CAT_VISIBLE_SUCCESS'			=>	'Bravo!<br />La cat&eacute;gorie est d&eacute;sormais visible pour les visiteurs du site web.',
			'FILE_CAT_HIDDEN_SUCCESS'			=>	'Bravo!<br />La cat&eacute;gorie est d&eacute;sormais masqu&eacute; pour les visiteurs du site web.',
			"FILE_ERROR_CHOOSE"					=>	"Vous devez d'abord choisir un fichier &agrave; charger depuis votre appareil",
			"FILE_CFRM_SENT"					=>	"Fichier charg&eacute; avec succ&egrave;s!",
			"FILE_ERROR_CANT_SEND"				=>	"D&eacute;sol&eacute;!<br />Impossible de charger votre fichier",
			"FILE_CLICK_PREVIEW"				=>	"Cliquez pour visualiser le contenu de votre fichier",
			"FILE_BTN_UPLOAD"					=>	"T&eacute;l&eacute;chargez le fichier",
			"FILE_NOT_ALLOWED"					=>	"n'est pas un type de fichier autoris&eacute;",
			"FILE_LBL_IMPORT"					=>	"Formulaire d'importation de fichier",
			"FILE_LBL_DESCR"					=>	"(NB : Fichiers CSV ou VCF uniquement)",
			"FILE_LBL_PLACEH"					=>	"Votre fichier de contacts",

			//Admin menu
			"FILE_ADMIN_MENU_DISPLAY"			=>	"Lister les fichier",
			"FILE_ADMIN_MENU_CREATE"			=>	"Ajouter un fichier",
			"FILE_ADMIN_MENU_CAT_DISPLAY"		=>	"Lister les cat&eacute;egories",
			"FILE_ADMIN_MENU_CAT_CREATE"		=>	"Ajouter une cat&eacute;egorie",

			//Main page display
			'FILE_HOME_BOX_ACCORDION'			=>	'Documentation',
			'FILE_SIDE_BOX_TITLE' 				=> 	'Fichiers',
			"FILE_BOX_TITLE" 					=> 	"Fichiers r&eacute;cents",
			"FILE_BOX_LINK"						=> 	"&raquo;Aller &agrave; la biblioth&egrave;que",
			"FILE_BOX_LINK_ALL"					=> 	"Tous les fichiers",
			"FILE_PAGE_TITLE"					=> 	"Espace T&eacute;l&eacute;chargement",
			"FILE_PAGE_HEADER"					=> 	"CABB :: Bibliot&egrave;que",
			"FILE_PAGE_CAT_HEADER"				=> 	"CABB :: Fichiers par cat&eacute;gories",
			"FILE_PAGE_BACK"					=> 	"Retour &agrave; la biblioth&egrave;que",
			"FILE_PJ"							=> 	"Pi&eacute;ce-jointe",
			"FILE_CAT_SIDE_BOX_TITLE"			=>	"Fichiers par cat&eacute;gories",
			"FILE_LOCATION"						=>	"Lieu",
			"NO_FILE"							=>	"Aucun fichier &agrave; afficher",
			"FILE_LBL_FILE"						=> 	"Fichier",
			"FILE_LBL_WIDTH"					=>	"Taille",
			"FILE_LBL_DLD"						=>	"T&eacute;l&eacute;chargez",
			"FILE_LBL_MORE"						=>	"&raquo; D&eacute;tails",
			"FILE_CAT_ERR"						=>	"Aucune cat&eacute;gorie &agrave; afficher",
            "FILE_LBL_DETAIL_DESCR"             =>  "D&eacute;tail du fichier",
            "FILE_LBL_TYPE"                     =>  "Type de fichier",
			"FILE_LBL_SIZE"                     =>  "Taille du fichier"
			)
	);