<?php
	$mod_lang_output	=	array_merge($lang_output, 
	array(
			//General
			'MODULE_NAME'							        =>	'<i class=\'fa fa-sitemap icon_info icon_color\'></i>&nbsp;Pages Manager',
			'MODULE_DESCR'							        =>	'Pages manager',
			'FORM_BUTTON_UPDATE'					        =>	'Update',
			'FORM_HELP_LEAVE_EMPTY'					        =>	'Leave blank if same',

			//Admin emails
			'ADMIN_EMAIL_NAME'						        =>	'DIGITRA Webmaster',
			'ADMIN_EMAIL_OBJECT'					        =>	'Your new Control Panel Account in our Website',
	    
			//Admin --	Tables
			'TABLE_HEADER_NAME' 				            => 	'Name',
			'TABLE_HEADER_LOGIN' 				            => 	'Login',
			'TABLE_HEADER_E-MAIL'				            => 	'E-mail',
			'TABLE_HEADER_STATUS'				            => 	'Category',
			'TABLE_HEADER_REG-DATE'				            => 	'Date of creation',
			'TABLE_HEADER_PUB-DATE'				            =>	'Date of publication',
			'TABLE_HEADER_EXP-DATE'				            =>	'Expire date',
			'TABLE_HEADER_AUTHOR'				            =>	'Author',
			'TABLE_HEADER_ACTION'				            => 	'Actions',
			'TABLE_HEADER_ACTIONS'				            => 	'Actions',
			'TABLE_HEADER_MODULES'				            => 	'Modules',
			'TABLE_HEADER_PAGES'				            => 	'Pages',
			'TABLE_HEADER_CATEGORY'				            =>	'Category',
			'TABLE_HEADER_TITLE'				            =>	'Title',
			'TABLE_HEADER_MENU_TITLE'			            =>	'Label',
			'TABLE_HEADER_MENU_ORDER'			            =>	'Order',
			'TABLE_HEADER_PAGE_LANGUAGE'		            =>	'Language',
			'TABLE_HEADER_MENU_CATEGORY'		            =>	'Menu category',
			'TABLE_HEADER_MENU_LINK'			            =>	'Link',
			'TABLE_HEADER_LAST-NAME'			            =>	'Last name',
			'TABLE_HEADER_FIRST-NAME'			            =>	'First name',
			'TABLE_HEADER_DESCRIPTION'			            =>	'Description',
			'TABLE_HEADER_POSITION'				            =>	'Position',
			'TABLE_HEADER_URL'					            =>	'Link(URL)',
			
			//Admin -- Forms
			'FORM_LABEL_CODE'					            =>	'Code',
			'FORM_LABEL_LANGUAGE'				            =>	'Language',
			'FORM_LABEL_LABEL'					            =>	'Label',
			'FORM_LABEL_TITLE'					            =>	'Title',
			'FORM_LABEL_CATEGORY'				            =>	'Category',
			'FORM_LABEL_DESCRIPTION'			            =>	'Description',
			'FORM_LABEL_LOGIN'					            =>	'Access code',
			'FORM_LABEL_USER-NAME'				            =>	'Login',
			'FORM_LABEL_PASSWORD'				            =>	'Password',
			'FORM_LABEL_PASSWORD2'				            =>	'Re-type the Password',
			'FORM_LABEL_E-MAIL'					            =>	'E-mail',
			'FORM_LABEL_FILE'					            =>	'File',
			'FORM_LABEL_FULL-NAME'				            => 	'Full name',
			'FORM_LABEL_LAST-NAME'				            =>	'Last name',
			'FORM_LABEL_FIRST-NAME'				            =>	'First name',
			'FORM_LABEL_PHONE-NUMBER'			            =>	'Phone number',
			'FORM_LABEL_ACCOUNT_ACTIVATE'		            =>	'Activate the account',
			'FORM_LABEL_PAGE_CONTENT'			            =>	'Page content',
			'FORM_LABEL_PAGE_TAGS'				            =>	'Keywords',
			'FORM_LABEL_PAGE_TITLE'				            =>	'Page title',
			'FORM_LABEL_PAGE_HEADER'			            =>	'Page header',
			'FORM_LABEL_SET_HOMEPAGE'			            =>	'Define as homepage',
			'FORM_LABEL_ADD_USER'				            =>	'Add a user account',
			'FORM_LABEL_DISPLAY'				            =>	'Display',
			'FORM_LABEL_PAGE_PARENT'			            =>	'Mother page',
			'FORM_LABEL_PAGE_ORDER'				            =>	'Define the order',
			'FORM_LABEL_PAGE_LANGUAGE'			            =>	'Language',
			'FORM_LABEL_MENU_CATEGORY'			            =>	'Menu type',
			'FORM_LABEL_MENU_LABEL'				            =>	'Menu label',
			'FORM_LABEL_END-DATE'				            =>	'Date of end',
			'FORM_LABEL_PAGES'					            =>	'The pages',
			'FORM_LABEL_SIGNATURE'				            =>	'Signature',
			'FORM_LABEL_MODULES'				            =>	'The modules',
			'FORM_LABEL_TAGS'					            =>	'Keywords',
			'FORM_LABEL_PUB-DATE'				            =>	'Date of publication',
			'FORM_LABEL_PJ'						            =>	'Attachment',
			'FORM_LABEL_URL'					            =>	'Link',
			'FORM_LABEL_MEMBER_FILE_IMPORT'		            =>	'Members file to be uploaded',
			'FORM_LABEL_TUITION_FILE_IMPORT'	            =>	'Tuition fees file to be uploaded',
			'FORM_LABEL_NOTE_FILE_IMPORT'		            =>	'Marks file to be uploaded',
			'FORM_VALUE_CATEGORY_1'				            =>	'Administrator',
			'FORM_VALUE_CATEGORY_2'				            =>	'Editor',
			'FORM_VALUE_SELECT_PAGE'			            =>	'Choose a page',
	        'FORM_VALUE_SELECT_LANG'			            =>	'Choose a language',
			'FORM_VALUE_SELECT'					            =>	'Select',
			'FORM_VALUE_CHOOSE'					            =>	'Choose',
			'FORM_LABEL_SEX'					            =>	'Sex',
			'FORM_VALUE_SEX_1'					            =>	'Male',
			'FORM_VALUE_SEX_2'					            =>	'Female',
			'FORM_VALUE_NONE_HOMEPAGE'			            =>	'None (For homepage)',
			'FORM_BUTTON_ADD_PAGE'				            =>	'Create a page',
			'FORM_BUTTON_ADD_CATEGORY'			            =>	'Add the category',
			'FORM_BUTTON_ADD_MEMBER'			            =>	'Add a member',
			'FORM_BUTTON_UPDATE_PAGE_CONTENT'	            =>	'Update contents',
			'FORM_BUTTON_UPDATE_MENU'			            =>	'Update the menu',
			'FORM_BUTTON_UPDATE_PAGE'			            =>	'Update the page',
			'FORM_BUTTON_UPDATE_CATEGORY'		            =>	'Update the category',
			'FORM_BUTTON_ASSIGN'				            =>	'Assign',
			'FORM_HELP_CRT_MAX'					            =>	'Max caracter',
			'FORM_HELP_CSV_ONLY'				            =>	'CSV files only',
	        'FORM_ERROR_LANG'                               =>  'Error!<br />You must choose a language first.',
	        'FORM_ERROR_NO_CAT'                             =>  'Error!<br />You must specify a category.',
			
			//Admin -- Headers
			'PAGE_HEADER_ADD_PAGE'						    =>	'Create a page',
			'PAGE_HEADER_ADD_CATEGORY'					    =>	'Add a category',
			'PAGE_HEADER_ADD_PAGE_CATEGORY'				    =>	'Add a user category',
			'PAGE_HEADER_UPDATE_MENU'					    =>	'Update the menu',
			'PAGE_HEADER_UPDATE_PAGE_CATEGORY'			    =>	'Update category',
			'PAGE_HEADER_UPDATE_CATEGORY'				    =>	'Update une category',
			'PAGE_HEADER_LIST_PAGES'					    =>	'Display pages',
			'PAGE_HEADER_LIST_PAGES_CATEGORIES'			    =>	'Display page categores',
			'PAGE_HEADER_LIST_MODULES'					    =>	'Display modules',
			'PAGE_HEADER_ASSIGN_PAGES_MODULES'			    =>	'Assign modules to pages',
			'PAGE_HEADER_EDIT_CONTENTS'					    =>	'Edit page contents',
			'PAGE_HEADER_LIST_CATEGORIES'				    =>	'Display page categories',
	    
			//Form validation msgs
			"PAGE_MSG_MENU_TITLE_REQUIRED"				   	=>	"D&eacute;sol&eacute;!<br />The title of the menu is required before continue.",
			"PAGE_MSG_MENU_SUCCESS"						   	=>	"Bravo!<br />Menu link successfully created!",
			"PAGE_MSG_MENU_UPDATE_SUCCESS"				   	=>	"Bravo!<br />Menu link successfully updated!",
			"PAGE_MSG_UPDATE_SUCCESS"					   	=>	"Bravo!<br />Page successfully updated!",
			"PAGE_MSG_DELETE_SUCCESS"					   	=>	"Bravo!<br />Page successfully deleted.",
			"PAGE_MSG_DELETE_IMPOSSIBLE"				   	=>	"Error!<br />We are unable to delete that page.",
			"PAGE_MSG_SHOW"								   	=>	"Bravo!<br />The page is now visible to the general public.",
			"PAGE_MSG_HIDE"								   	=>	"Bravo!<br />The page is now hidden to the general public.",
			"PAGE_MSG_ASSIGNATION_DELETE_SUCCESS"		   	=>	"Bravo!<br />Association successfully deleted.",
			"PAGE_MSG_ASSIGNATION_DELETE_ERROR"			   	=>	"D&eacute;sol&eacute;!<br />We are unable to delete the association.",
			"PAGE_MSG_MODULE_SELECT_ERROR"				   	=>	"Error!<br />You must absolutely select a page and a module before continue!",
			"PAGE_MSG_ASSIGNATION_EXISTS"				   	=>	"D&eacute;sol&eacute;!<br />This assignation exists already.",
			"PAGE_MSG_ASSIGNATION_SUCCESS"				   	=>	"Bravo!<br />Page and module selected have been successfully associated",
			
			//Admin menu
			"PAGE_ADMIN_MENU_DISPLAY"						=>	"Afficher les pages",
			"PAGE_ADMIN_MENU_CREATE"						=>	"Cre&eacute;er une page",
			"PAGE_ADMIN_MENU_CONTENT_EDIT"					=>	"Editer les contenus",
			"PAGE_ADMIN_MENU_MODULE_ASSIGN"					=>	"Assigner un module")
	);