<?php
$mod_lang_output	=	array_merge($lang_output, 
	array(
		//General
		'MODULE_NAME'								=>	'<i class=\'fa fa-quote-left icon_info icon_color\'></i>&nbsp;INTERVIEWe Manager',
		'MODULE_DESCR'								=>	'Gestionnaire des citations quotidiennes',
		'FORM_BUTTON_UPDATE'						=>	'Mettre &agrave; jour',
		'FORM_HELP_LEAVE_EMPTY'						=>	'Laisser vide si identique',
		'FORM_HELP_CRT_MAX'							=>	'Caract&egrave;res max.',
		'FORM_LABEL_LANGUAGE'						=>	'Langue',
		'FORM_LABEL_SEX'							=>	'Sexe',
		'FORM_VALUE_CHOOSE'							=> 	'Choisir',
		'FORM_VALUE_SEX_1'							=>	'Masculin',
		'FORM_VALUE_SEX_2'							=>	'Feminin',
			
		//Admin --	Tables
		'TABLE_HEADER_TITLE' 						=> 	'Titre',
		'TABLE_HEADER_AUTHOR' 						=> 	'Auteur',
		'TABLE_HEADER_DATE-CREA'					=> 	'Cr&eacute;&eacute; le',
		'TABLE_HEADER_DATE-START'					=> 	'D&eacute;but',
		'TABLE_HEADER_DATE-END'						=> 	'Fin',
		'TABLE_HEADER_ACTION'						=> 	'Actions',
		'TABLE_HEADER_CATEGORY'						=>	'Cat&eacute;gorie',
		'TABLE_HEADER_AUTHOR_GROUP'					=>	'Groupe',
		'TABLE_HEADER_DESCRIPTION'					=>	'Description',
		'TABLE_HEADER_INTERVIEW_POSITION'			=>	'Position sur la page',
		'TABLE_HEADER_INTERVIEW_REFERENCE'			=>	'R&eacute;f&eacute;rence',
		'TABLE_HEADER_INTERVIEW_CONTENT'			=>	'Contenu',
			
		//Admin -- Forms
		'FORM_LABEL_CATEGORY'						=>	'Cat&eacute;gorie',
		'FORM_LABEL_INTERVIEW_CATEGORY'				=>	'Rubrique',
		'FORM_LABEL_CODE'							=>	'Code',
		'FORM_LABEL_TITLE'							=>	'Titre',
		'FORM_LABEL_INTERVIEW_POSITION'				=>	'Position sur la page',
		'FORM_LABEL_INTERVIEW_PAGE'					=>	'Page pour citation',
		'FORM_LABEL_INTERVIEW_HEADER'				=>	'Chapeau',
		'FORM_LABEL_INTERVIEW_TAGS'					=>	'Mots-cl&eacute;s',
		'FORM_LABEL_INTERVIEW_CONTENT'				=>	'Contenu principal',
		'FORM_LABEL_INTERVIEW_TITLE'				=>	'Titre',
		'FORM_LABEL_LABEL'							=>	'Libell&eacute;',
		'FORM_LABEL_DATE-PUB'						=>	'Date de publication',
		'FORM_LABEL_DATE-CREA'						=>	'Date de cr&eacute;ation',
		'FORM_LABEL_INTERVIEW_THUMBNAIL'			=>	'Imagette',
		'FORM_LABEL_FIRST-NAME'						=>	'Pr&eacute;nom',
		'FORM_LABEL_LAST-NAME'						=>	'Nom',
		'FORM_LABEL_GROUP'							=>	'Groupe',
		'FORM_LABEL_AUTHOR_GROUP'					=>	'Groupe d\'auteurs',
		'FORM_LABEL_DESCRIPTION'					=>	'Description',
		'FORM_LABEL_INTERVIEW_IMG_HEADER'			=>	'Image d\'ent&ecirc;te',
		'FORM_LABEL_INTERVIEW_EXP-DATE'				=>	'Date d\'expiration de la citation',
		'FORM_LABEL_EXP-DATE'						=>	'Date d\'expiration',
		'FORM_LABEL_ADD_INTERVIEW'					=>	'Ajouter un citation',
		'FORM_BUTTON_ADD_INTERVIEW'					=>	'Ajouter une citation',
		'FORM_BUTTON_ADD_INTERVIEW_AUTHOR'			=>	'Ajouter un auteur',
		'FORM_BUTTON_ADD_CATEGORY'					=>	'Ajouter la cat&eacute;gorie',
		'FORM_BUTTON_ADD_AUTHOR_GROUP'				=>	'Ajouter un groupe d\'auteurs',
		'FORM_BUTTON_UPDATE_AUTHOR_GROUP'			=>	'Modifier un groupe d\'auteurs',
		'FORM_BUTTON_UPDATE_INTERVIEW'				=>	'Modifier la citation',
			
		//Admin -- Headers
		'PAGE_HEADER_ADD_INTERVIEW'					=>	'Ajouter une citation',
		'PAGE_HEADER_ADD_INTERVIEW_CATEGORY'		=>	'Ajouter une cat&eacute;gorie de citation',
		'PAGE_HEADER_ADD_AUTHOR_GROUP'				=>	'Ajouter un groupe d\'auteur',
		'PAGE_HEADER_ADD_INTERVIEW_AUTHOR'			=>	'Ajouter un auteur',
		'PAGE_HEADER_UPDATE_AUTHORS_GROUP'			=>	'Modifier un groupe d\'auteurs',
		'PAGE_HEADER_UPDATE_INTERVIEW'				=>	'Modifier la citation',
		'PAGE_HEADER_UPDATE_INTERVIEW_CATEGORY'		=>	'Modifier une cat&eacute;gorie de citation',
		'PAGE_HEADER_UPDATE_INTERVIEW_AUTHOR'		=>	'Modifier un auteur',
		'PAGE_HEADER_LIST_INTERVIEWS'				=>	'Afficher les citations',
		'PAGE_HEADER_LIST_INTERVIEW_CATEGORIES'		=>	'Afficher les cat&eacute;gories',
		'PAGE_HEADER_LIST_INTERVIEW_COMMENTS'		=>	'Afficher les commentaires',
		'PAGE_HEADER_LIST_INTERVIEW_AUTHORS'		=>	'Afficher les auteurs',
		'PAGE_HEADER_LIST_AUTHOR_GROUPS'			=>	'Afficher les groupes d\'auteurs',
		
		'PAGE_LINK_ADD_INTERVIEW_AUTHOR_GROUP'		=>	'Ajouter un groupe d\'auteur',
		'PAGE_LINK_ADD_INTERVIEW_AUTHOR'			=>	'Ajouter un auteur',

		//Admin menu
		"INTERVIEW_ADMIN_MENU_DISPLAY"				=>	"Interview requests",
		"INTERVIEW_ADMIN_MENU_CREATE"				=>	"Add request",
		"INTERVIEW_ADMIN_MENU_CAT_DISPLAY"			=>	"Show categories",
		"INTERVIEW_ADMIN_MENU_CAT_CREATE"			=>	"Add category",
		
		//Main page display
		"INTERVIEW_RBOX_TITLE" 						=> 	"Interviews",
		"INTERVIEW_BOX_TITLE" 						=> 	"Last interviews",
		"INTERVIEW_BOX_LINK"						=> 	"&raquo;Go to interviews",
		"INTERVIEW_BOX_LINK_ALL"					=> 	"All interviews",
		"INTERVIEW_PAGE_TITLE"						=> 	"Interviews",
		"INTERVIEW_PAGE_HEADER"						=> 	"NWR :: Interviews",
		"INTERVIEW_PAGE_CAT_HEADER"					=> 	"CABB :: Citations par cat&eacute;gories",
		"INTERVIEW_PAGE_BACK"						=> 	"Retour aux citations",
		"INTERVIEW_PJ"								=> 	"Pi&eacute;ce-jointe",
		"INTERVIEW_RBOX_CAT_TITLE"					=>	"Citations par cat&eacute;gories",
		"INTERVIEW_LOCATION"						=>	"Location",
		"NO_INTERVIEW"								=>	"No interview request to be displayed",
		"NO_INTERVIEW_CATEGORY"						=>	"Aucune categorie d\'citation &agrave; afficher",
		
		//Citation
		"INTERVIEW_RBOX_TITLE" 						=> 	"Le babillard du CABB",
		"INTERVIEW_BOX_TITLE" 						=> 	"La une du babillard",
		"INTERVIEW_BOX_LINK"						=> 	"&raquo;Toutes les citations",
		"INTERVIEW_BOX_LINK_ALL"					=> 	"Toutes les citations",
		"INTERVIEW_PAGE_TITLE"						=> 	"Le babillard du CABB",
		"INTERVIEW_PAGE_HEADER"						=> 	"CABB :: Le babillard",
		"INTERVIEW_PAGE_CAT_HEADER"					=> 	"CABB :: Citations et communiqu&eacute;s par cat&eacute;gories",
		"INTERVIEW_PAGE_BACK"						=> 	"&raquo;Retour au babillard",
		"INTERVIEW_PJ"								=> 	"Pi&eacute;ce-jointe",
		"INTERVIEW_RBOX_CAT_TITLE"					=>	"Citations par cat&eacute;gories",

	    "ITW_NAME"									=>	"Name",
	    "ITW_RANK"									=>	"Rank",
	    "ITW_SUBJECT"								=>	"Object of your visit",
	    "ITW_EMAIL"									=>	"E-mail",
	    "ITW_PHONE"									=>	"Phone number",
	    "ITW_CNI"									=>	"ID/Passport Number",
	    "ITW_DATE"									=>	"Proposed date and time for the appointment",
	    "ITW_BTN_OK"								=>	" Book an interview ",
	    "ITW_BTN_BOOK_CFRM"							=>	"You are about to book for an interview with the Governor. Would you like to continue?",
	    "ITW_ERROR_REQUIRED"						=>	"Fields marked with (*) are mandatory",
	    "ITW_ERROR_DATE"							=>	"Sorry, you haven't pick a correct date",
	    "ITW_INSERT_CFRM"							=>	"Your request has been taken into consideration. <br />You'll receive a confirmation e-mail very soon.<br />Thank you.",
	    "ITW_ERROR_EXIST"							=>	"Sorry, your request is already booked",
	    "ITW_MAIL_FROM"								=>	"info@northwest-cameroon.com",
	    "ITW_MAIL_SUBJECT"							=>	"[North-West Region, Cameroon] - Request for an interview",
	    "ITW_MAIL_CONTENT"							=>	"<p>Hello, dear visitor,</p><p>You requested to be received by the Governor of the North-West Region through our website.<br />Your request is currently under processing and we shall let you informed as soon as the Governor is ready to receive you.</p><p>Cordially.</p>",
	    "ITW_CAPTCHA_LABEL"                			=>   "Type code in the box below"
	)
		
);