<?php
$mod_lang_output	=	array_merge($lang_output, 
	array(
				
				'CONTACT_MAIL_SUBJECT'		        =>	'Online e-mail from',
	            'FRM_CAPTCHA_LABEL'                 =>  'Type code in the box below',
        	    "C_FIRST_NAME"						=> 	"First name",
        	    "C_LAST_NAME"						=> 	"Last name",
        	    "C_EMAIL"							=> 	"E-mail",
        	    "C_PHONE1"							=> 	"Telephone land line ",
        	    "C_PHONE2"							=> 	"Mobile phone number",
        	    "C_COM_NAME"						=> 	"Name of the company",
        	    "C_WEBSITE"							=> 	"Web site",
        	    "C_COUNTRY"							=> 	"Choose your country here",
        	    "C_TOWN"							=> 	"Town",
        	    "C_DESCRIBE"						=> 	"What the best describe your needs",
        	    "C_DESCRIBE_1"						=> 	"Become reseller",
        	    "C_DESCRIBE_2"						=> 	"PC to Phone",
        	    "C_DESCRIBE_3"						=> 	"Mobile VoIP",
        	    "C_DESCRIBE_4"						=> 	"Calling Cards",
        	    "C_DESCRIBE_5"						=> 	"Callback",
        	    "C_DESCRIBE_6"						=> 	"Callshop Solutions",
        	    "C_DESCRIBE_7"						=> 	"Need to buy some routes",
        	    "C_DESCRIBE_8"						=> 	"Have routes to sell",
        	    "C_DESCRIBE_9"						=> 	"Become a reseller",
        	    "C_DESCRIBE_10"						=> 	"Hosted Softswitch",
        	    "C_CONTACT_MEDIA"					=> 	"You wish to be contacted via",
        	    "C_CONTACT_MEDIA1"					=> 	"E-mail",
        	    "C_CONTACT_MEDIA2"					=> 	"Phone call",
        	    "C_CONTACT_MEDIA3"					=> 	"SMS",
        	    "C_TIME_CALL"						=> 	"Recommanded calling time",
        	    "C_ACTUAL_SOL"						=> 	"Quelle solution utilisez-vous actuellement?",
        	    "C_TIME_WORK"						=> 	"Votre entreprise est dans le domaine depuis combien de temps?",
        	    "C_WHEN"							=> 	"Quand comptez-vous d&eacute;ployer nos solutions qui vous interessent?",
        	    "C_WHEN1"							=> 	"in 03 months time",
        	    "C_WHEN2"							=> 	"between 03 and 06 months time",
        	    "C_WHEN3"							=> 	"in not less than 06 months",
        	    "C_HOW_HEARD"						=> 	"Comment avez-vous entendu parl&eacute; de nous?",
        	    "C_HOW_HEARD1"						=> 	"Repr&eacute;sentant commercial / Revendeur",
        	    "C_HOW_HEARD2"						=> 	"News paper / magazine",
        	    "C_HOW_HEARD3"						=> 	"Prospectus ",
        	    "C_HOW_HEARD4"						=> 	"Google",
        	    "C_HOW_HEARD5"						=> 	"Web research",
        	    "C_OTHER"							=> 	"Please specify if others",
        	    "C_COMMENT"							=> 	"Comments or suggestions",
        	    "C_CONFIRM"							=> 	"The information you filled must be true so that we'll be able to contact you through your e-mail address. Do you wish to continue?",
        	    "C_REQUIRED"						=> 	"Fields with (*) are mandatory",
        	    "C_OK"								=> 	"Merci<br />Votre message a &eacute;t&eacute; correctement envoy&eacute;",
        	    "C_MAIL_TO"							=> 	"contact@northwest-cameroon.com"
	)
		
);