<?php
$mod_lang_output	=	array_merge($lang_output, 
	array(
				
	    'CONTACT_MAIL_SUBJECT'		                =>	'E-mail en ligne de',
	    'FRM_CAPTCHA_LABEL'                         =>   'Saisir code de v&eacute;rification',
	    //frm  label : Contact
	    "C_FIRST_NAME"								=> 	"Pr&eacute;nom",
	    "C_LAST_NAME"								=> 	"Nom",
	    "C_EMAIL"									=> 	"E-mail",
	    "C_PHONE1"									=> 	"T&eacute;l&eacute;phone fixe",
	    "C_PHONE2"									=> 	"T&eacute;l&eacute;phone mobile",
	    "C_COM_NAME"								=> 	"Nom de l'entreprise",
	    "C_WEBSITE"									=> 	"Site web",
	    "C_COUNTRY"									=> 	"Choisir votre pays ici",
	    "C_TOWN"									=> 	"Ville",
	    "C_DESCRIBE"								=> 	"Qu'est-ce qui d&eacute;crit le mieux vos besoins?",
	    "C_DESCRIBE_1"								=> 	"Devenir revendeur",
	    "C_DESCRIBE_2"								=> 	"PC &agrave; T&eacute;l&eacute;phone",
	    "C_DESCRIBE_3"								=> 	"VoIP mobile",
	    "C_DESCRIBE_4"								=> 	"Cartes d'Appel",
	    "C_DESCRIBE_5"								=> 	"Callback",
	    "C_DESCRIBE_6"								=> 	"Solutions Callshop",
	    "C_DESCRIBE_7"								=> 	"Besoin d'acheter des routes",
	    "C_DESCRIBE_8"								=> 	"Dispose de routes &agrave; vendre",
	    "C_DESCRIBE_9"								=> 	"Devenir revendeur",
	    "C_DESCRIBE_10"								=> 	"Hosted Softswitch",
	    "C_CONTACT_MEDIA"							=> 	"Vous souhaitez être contact&eacute;s via",
	    "C_CONTACT_MEDIA1"							=> 	"E-mail",
	    "C_CONTACT_MEDIA2"							=> 	"Appel t&eacute;l&eacute;phonique",
	    "C_CONTACT_MEDIA3"							=> 	"SMS",
	    "C_TIME_CALL"								=> 	"Moment d'appel recommand&eacute;",
	    "C_ACTUAL_SOL"								=> 	"Quelle solution utilisez-vous actuellement?",
	    "C_TIME_WORK"								=> 	"Votre entreprise est dans le domaine depuis combien de temps?",
	    "C_WHEN"									=> 	"Quand comptez-vous d&eacute;ployer nos solutions qui vous interessent?",
	    "C_WHEN1"									=> 	"dans 03 mois",
	    "C_WHEN2"									=> 	"dans 03 &agrave; 06 mois",
	    "C_WHEN3"									=> 	"dans plus de 06 months",
	    "C_HOW_HEARD"								=> 	"Comment avez-vous entendu parl&eacute; de nous?",
	    "C_HOW_HEARD1"								=> 	"Repr&eacute;sentant commercial / Revendeur",
	    "C_HOW_HEARD2"								=> 	"Journal / magazine",
	    "C_HOW_HEARD3"								=> 	"Prospectus ",
	    "C_HOW_HEARD4"								=> 	"Google",
	    "C_HOW_HEARD5"								=> 	"Recherche sur le web",
	    "C_OTHER"									=> 	"Sp&eacute;cifiez si autre svp",
	    "C_COMMENT"									=> 	"Commentaire ou suggestion",
	    "C_CONFIRM"									=> 	"Ces informations doivent &ecirc;tre exactes et nous parviendront par e-mail. &Ecirc;tes-vous s&ucirc;r de vouloir continuer?",
	    "C_REQUIRED"								=> 	"Les champs avec ast&eacute;rix (*) sont obligatoires",
	    "C_OK"										=> 	"Merci<br />Votre message a &eacute;t&eacute; correctement envoy&eacute;",
	    "C_MAIL_TO"									=> 	"contact@northwest-cameroon.com"
	)
		
);