<?php
	$mod_lang_output = array_merge($lang_output,
			array( 
			//General
			'MODULE_NAME'						=>	'<i class=\'fa fa-indent icon_info icon_color\'></i>&nbsp;News Manager',
			'MODULE_DESCR'						=>	'Stories section manager',
			'FORM_BUTTON_UPDATE'				=>	'Update',
			'FORM_HELP_LEAVE_EMPTY'				=>	'Leave empty if same',
			'FORM_HELP_CRT_MAX'					=>	'Max. characters',
			'FORM_LABEL_LANGUAGE'				=>	'Language',
			'FORM_LABEL_SEX'					=>	'Sex',
			'FORM_VALUE_CHOOSE'					=> 	'Choose',
			'FORM_VALUE_SEX_1'					=>	'Male',
			'FORM_VALUE_SEX_2'					=>	'Female',
			
			//Admin --	Tables
			'TABLE_HEADER_TITLE' 				=> 	'Title',
			'TABLE_HEADER_AUTHOR' 				=> 	'Author',
			'TABLE_HEADER_DATE-CREA'			=> 	'Creation date',
			'TABLE_HEADER_DATE-START'			=> 	'Start date',
			'TABLE_HEADER_DATE-END'				=> 	'End date',
			'TABLE_HEADER_ACTION'				=> 	'Actions',
			'TABLE_HEADER_CATEGORY'				=>	'Category',
			'TABLE_HEADER_AUTHOR_GROUP'			=>	'Group',
			'TABLE_HEADER_DESCRIPTION'			=>	'Description',
			
			//Admin -- Forms
			'FORM_LABEL_CATEGORY'				=>	'Category',
			'FORM_LABEL_NEWS_CATEGORY'			=>	'News category',
			'FORM_LABEL_CODE'					=>	'Code',
			'FORM_LABEL_TITLE'					=>	'Title',
			'FORM_LABEL_NEWS_AUTHOR'			=>	'Author',
			'FORM_LABEL_HEADER'					=>	'Heading',
			'FORM_LABEL_NEWS_HEADER'			=>	'Heading',
			'FORM_LABEL_NEWS_TAGS'				=>	'Keywords',
			'FORM_LABEL_NEWS_CONTENT'			=>	'Main content',
			'FORM_LABEL_NEWS_TITLE'				=>	'Title',
			'FORM_LABEL_LABEL'					=>	'Label',
			'FORM_LABEL_DATE-PUB'				=>	'Date of publication',
			'FORM_LABEL_DATE-CREA'				=>	'Date of creation',
			'FORM_LABEL_NEWS_THUMBNAIL'			=>	'Thumbnail',
			'FORM_LABEL_FIRST-NAME'				=>	'First name',
			'FORM_LABEL_LAST-NAME'				=>	'Last name',
			'FORM_LABEL_GROUP'					=>	'Group',
			'FORM_LABEL_AUTHOR_GROUP'			=>	'Author\'s group',
			'FORM_LABEL_DESCRIPTION'			=>	'Description',
			'FORM_LABEL_NEWS_IMG_HEADER'		=>	'Headline image',
			'FORM_LABEL_ADD_NEWS'				=>	'Add a story',
			'FORM_BUTTON_ADD_NEWS'				=>	'Add a story',
			'FORM_BUTTON_ADD_NEWS_AUTHOR'		=>	'Add an author',
			'FORM_BUTTON_ADD_CATEGORY'			=>	'Add the category',
			'FORM_BUTTON_ADD_AUTHOR_GROUP'		=>	'Add a group of authors',
			'FORM_BUTTON_UPDATE_AUTHOR_GROUP'	=>	'Update a group of authors',
			'FORM_BUTTON_UPDATE_NEWS'			=>	'Update the story',
			
			//Admin -- Headers
			'PAGE_HEADER_ADD_NEWS'				=>	'Add a story',
			'PAGE_HEADER_ADD_NEWS_CATEGORY'		=>	'Add a story category',
			'PAGE_HEADER_ADD_AUTHOR_GROUP'		=>	'Insert a group of authors ',
			'PAGE_HEADER_ADD_NEWS_AUTHOR'		=>	'Insert an author',
			'PAGE_HEADER_UPDATE_AUTHORS_GROUP'	=>	'Update a group of authors',
			'PAGE_HEADER_UPDATE_NEWS'			=>	'Update the story',
			'PAGE_HEADER_UPDATE_NEWS_CATEGORY'	=>	'Update the category',
			'PAGE_HEADER_UPDATE_NEWS_AUTHOR'	=>	'Update an author',
			'PAGE_HEADER_LIST_NEWS'				=>	'Display stories',
			'PAGE_HEADER_LIST_NEWS_CATEGORIES'	=>	'Display categories',
			'PAGE_HEADER_LIST_NEWS_COMMENTS'	=>	'Display comments',
			'PAGE_HEADER_LIST_NEWS_AUTHORS'		=>	'Display authors',
			'PAGE_HEADER_LIST_AUTHOR_GROUPS'	=>	'Display author\'s groups',
	
			'PAGE_LINK_ADD_NEWS_AUTHOR_GROUP'	=>	'Add a group of authors',
			'PAGE_LINK_ADD_NEWS_AUTHOR'			=>	'Add an author',
					
			//Admin -- Validations
			'NEWS_FIELDS_MANDATORY'				=>	'Sorry!<br />You must fill all the mandatory fields.',
			'NEWS_DATE_NOT_VALID'				=>	'Sorry!<br />The date inserted is not a valid one.',
			'NEWS_TITLE_EXISTS'					=>	'Sorry!<br />This title exists already. Please try with another one...!',
			'NEWS_EXISTS'						=>	'Sorry!<br />This story already found in our database!',
			'NEWS_TOP_STORY_IMG'				=>	'Sorry!<br />You must specify a picture (gif/jpg/png formats) for the homepage top stories.',
			'NEWS_FILE_TYPE_ERROR'				=>	'Sorry!<br />Incorrect file type',
			'NEWS_INSERT_SUCCESS_THUMB'			=>	'Congratulations!<br />The story has been successfuly recorded in our database with a thumbnail!',
			'NEWS_INSERT_SUCCESS'				=>	'Congratulations!<br />The story has been successfuly recorded in our database!',
			'NEWS_UPDATE_SUCCESS'				=>	'Congratulations!<br />Story successfully updated.',
			'NEWS_DELETE_SUCCESS'				=>	'Congratulations!<br />The story has been successfully deleted.',
			'NEWS_PUBLISH_OK'					=>	'Congratulations!<br />The story is now visible for the website visitors.',
			'NEWS_HIDE_OK'						=>	'Congratulations!<br />The story is now hidden for the website visitors.',
			'NEWSCAT_CODE_MANDATORY'			=>	'Sorry!<br />The code for the category is mandatory.',
			'NEWSCAT_LABEL_MANDATORY'			=>	'Sorry!<br />You must specify a label for the news category.',
			'NEWSCAT_EXISTS'					=>	'Sorry!<br />This category exists already.',
			'NEWSCAT_SUCCESS'					=>	'Congratulations!<br />News category successfully created.',
			'NEWSCAT_DELETE_SUCCESS'			=>	'Congratulations!<br />Category successfully deleted.',
			'NEWSCAT_UPDATE_SUCCESS'			=>	'Congratulations!<br />News category successfully updated.',
			'NEWSCAT_PUBLISH'					=>	'Congratulations!<br />Category set visible. All the related stories shall be visible to the website visitors.',
			'NEWSCAT_HIDE'						=>	'Congratulations!<br />Catgory set invisible. All the related stories shall be hidden to the website visitors!',
			'NEWS_AUTHOR_GROUP_EXISTS'			=>	'Sorry!<br />This author group exists already.',
			'NEWS_AUTHOR_GROUP_EMPTY'			=>	'Sorry!<br />You must fill the text field before proceeding.',
			'NEWS_AUTHOR_GROUP_SUCCESS'			=>	'Congratulations!<br />Author group successfully created.',
			'NEWS_AUTHOR_GROUP_UPDATE_SUCCESS'	=>	'Congratulations!<br />Author group successfully updated.',
			'NEWS_AUTHOR_GROUP_DELETE_SUCCESS'	=>	'Congratulations!<br />Authors group successfully deleted.',
			'NEWS_AUTHOR_UPDATE_SUCCESS'		=>	'Congratulations!<br />Author\'s informations successfully updated.',
			'NEWS_AUTHOR_DELETE_SUCCESS'		=>	'Congratulations!<br />Author successfully deleted.',
			'NEWS_AUTHOR_SUCCESS'				=>	'Congratulations!<br />Author created successfully.',
			'NEWS_AUTHOR_EXISTS'				=>	'Sorry!<br />This author is already registered.',
			'NEWS_AUTHOR_FIRST_NAME_ERROR'		=>	'Error!<br />You must provide a first or last name for the author.',
			'NEWS_AUTHOR_SEX_ERROR'				=>	'Sorry!<br />You must choose a sex for the author.',
			'NEWS_COMMENT_PUBLISH'				=>	'Congratulations!<br />The comment is now visible to the website visitors.',
			'NEWS_COMMENT_HIDE'					=>	'Congratulations!<br />The comment shall not more appear in the website.',
			'NEWS_COMMENT_DELETE'				=>	'Congratulations!<br />The comment has been successfully deleted.',
			

			//Main page display
			"NEWS_SIDE_BOX_TITLE" 				=> 	"News",
			"NEWS_BOX_TITLE" 					=> 	"Top stories",
			"NEWS_BOX_LINK"						=> 	"&raquo;Go to the news",
			"NEWS_BOX_LINK_ALL"					=> 	"See all stories",
			"NEWS_PAGE_TITLE"					=> 	"MINDDEVEL News",
			"NEWS_PAGE_HEADER"					=> 	"MINDDEVEL :: News",
			"NEWS_PAGE_CAT_HEADER"				=> 	"MINDDEVEL :: News by categories",
			"NEWS_PAGE_BACK"					=> 	"Back to the news",
			"NEWS_PJ"							=> 	"Attachment",
			"NEWS_CAT_SIDE_BOX_TITLE"			=>	"News by category",
			"NEWS_CAT_ERR"						=>	"No category",
			"NEWS_LOCATION"						=>	"Link",
			"NO_NEWS"							=>	"No story to be displayed.",
			"NEWS_MORE"                         =>  "Read more",
			"NEWS_HOME_TITLE"                   =>  "Headlines"
			)
	);