<?php
	$mod_lang_output = array_merge($lang_output,
			array( 
			//General
			'MODULE_NAME'						=>	'<i class=\'fa fa-indent icon_info icon_color\'></i>&nbsp;News Manager',
			'MODULE_DESCR'						=>	'Gestionnaire des news',
			'FORM_BUTTON_UPDATE'				=>	'Mettre &agrave; jour',
			'FORM_HELP_LEAVE_EMPTY'				=>	'Laisser vide si identique',
			'FORM_HELP_CRT_MAX'					=>	'Caract&egrave;res max.',
			'FORM_LABEL_LANGUAGE'				=>	'Langue',
			'FORM_LABEL_SEX'					=>	'Sexe',
			'FORM_VALUE_CHOOSE'					=> 	'Choisir',
			'FORM_VALUE_SEX_1'					=>	'Masculin',
			'FORM_VALUE_SEX_2'					=>	'Feminin',
			
			//Admin --	Tables
			'TABLE_HEADER_TITLE' 				=> 	'Titre',
			'TABLE_HEADER_AUTHOR' 				=> 	'Auteur',
			'TABLE_HEADER_DATE-CREA'			=> 	'Cr&eacute;&eacute; le',
			'TABLE_HEADER_DATE-START'			=> 	'D&eacute;but',
			'TABLE_HEADER_DATE-END'				=> 	'Fin',
			'TABLE_HEADER_ACTION'				=> 	'Actions',
			'TABLE_HEADER_CATEGORY'				=>	'Cat&eacute;gorie',
			'TABLE_HEADER_AUTHOR_GROUP'			=>	'Groupe',
			'TABLE_HEADER_DESCRIPTION'			=>	'Description',
			
			//Admin -- Forms
			'FORM_LABEL_CATEGORY'				=>	'Cat&eacute;gorie',
			'FORM_LABEL_NEWS_CATEGORY'			=>	'Rubrique',
			'FORM_LABEL_CODE'					=>	'Code',
			'FORM_LABEL_TITLE'					=>	'Titre',
			'FORM_LABEL_NEWS_AUTHOR'			=>	'Auteur',
			'FORM_LABEL_HEADER'					=>	'Chapeau',
			'FORM_LABEL_NEWS_HEADER'			=>	'Chapeau',
			'FORM_LABEL_NEWS_TAGS'				=>	'Mots-cl&eacute;s',
			'FORM_LABEL_NEWS_CONTENT'			=>	'Contenu principal',
			'FORM_LABEL_NEWS_TITLE'				=>	'Titre',
			'FORM_LABEL_LABEL'					=>	'Libell&eacute;',
			'FORM_LABEL_NEWS_DATE-PUB'			=>	'Date de publication',
			'FORM_LABEL_NEWS_DATE-CREA'			=>	'Date de cr&eacute;ation',
			'FORM_LABEL_NEWS_THUMBNAIL'			=>	'Imagette',
			'FORM_LABEL_FIRST-NAME'				=>	'Pr&eacute;nom',
			'FORM_LABEL_LAST-NAME'				=>	'Nom',
			'FORM_LABEL_GROUP'					=>	'Groupe',
			'FORM_LABEL_AUTHOR_GROUP'			=>	'Groupe d\'auteurs',
			'FORM_LABEL_DESCRIPTION'			=>	'Description',
			'FORM_LABEL_NEWS_IMG_HEADER'		=>	'Image d\'ent&ecirc;te',
			'FORM_LABEL_ADD_NEWS'				=>	'Ajouter un article',
			'FORM_BUTTON_ADD_NEWS'				=>	'Ajouter un article',
			'FORM_BUTTON_ADD_NEWS_AUTHOR'		=>	'Ajouter un auteur',
			'FORM_BUTTON_ADD_CATEGORY'			=>	'Ajouter la cat&eacute;gorie',
			'FORM_BUTTON_ADD_AUTHOR_GROUP'		=>	'Ajouter un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_AUTHOR_GROUP'	=>	'Modifier un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_NEWS'			=>	'Modifier l\'article',
			
			//Admin -- Headers
			'PAGE_HEADER_ADD_NEWS'				=>	'Ajouter un article',
			'PAGE_HEADER_ADD_NEWS_CATEGORY'		=>	'Ajouter une cat&eacute;gorie d\'article',
			'PAGE_HEADER_ADD_AUTHOR_GROUP'		=>	'Ajouter un groupe d\'auteur',
			'PAGE_HEADER_ADD_NEWS_AUTHOR'		=>	'Ajouter un auteur',
			'PAGE_HEADER_UPDATE_AUTHORS_GROUP'	=>	'Modifier un groupe d\'auteurs',
			'PAGE_HEADER_UPDATE_NEWS'			=>	'Modifier l\'article',
			'PAGE_HEADER_UPDATE_NEWS_CATEGORY'	=>	'Modifier la cat&eacute;gorie',
			'PAGE_HEADER_UPDATE_NEWS_AUTHOR'	=>	'Modifier un auteur',
			'PAGE_HEADER_LIST_NEWS'				=>	'Afficher les articles',
			'PAGE_HEADER_LIST_NEWS_CATEGORIES'	=>	'Afficher les cat&eacute;gories',
			'PAGE_HEADER_LIST_NEWS_COMMENTS'	=>	'Afficher les commentaires',
			'PAGE_HEADER_LIST_NEWS_AUTHORS'		=>	'Afficher les auteurs',
			'PAGE_HEADER_LIST_AUTHOR_GROUPS'	=>	'Afficher les groupes d\'auteurs',
	
			'PAGE_LINK_ADD_NEWS_AUTHOR_GROUP'	=>	'Ajouter un groupe d\'auteur',
			'PAGE_LINK_ADD_NEWS_AUTHOR'			=>	'Ajouter un auteur',
					
			//Admin -- Validations
			'NEWS_FIELDS_MANDATORY'				=>	'Erreur!<br />Vous devez remplir tous les champs obligatoires.',
			'NEWS_DATE_NOT_VALID'				=>	'Erreur!<br />La date choisie n\'est pas valide.',
			'NEWS_TITLE_EXISTS'					=>	'Erreur!<br />Ce titre existe d&eacute;j&agrave;. Veuillez essayez avec un autre...!',
			'NEWS_EXISTS'						=>	'Erreur!<br />Cette news existe d&eacute;j&agrave; dans la base de donn&eacute;es!',
			'NEWS_TOP_STORY_IMG'				=>	'Erreur!<br />Vous devez sp&eacute;cifier une image (gif/jpg/png formats) pour la une en page d\'accueil.',
			'NEWS_FILE_TYPE_ERROR'				=>	'Erreur!<br />Type de fichier incorrect.',
			'NEWS_INSERT_SUCCESS_THUMB'			=>	'Bravo!<br />News enregistr&eacute;e avec succ&egrave;s avec une imagette!',
			'NEWS_INSERT_SUCCESS'				=>	'Bravo!<br />News enregistr&eacute;e avec succ&egrave;s.',
			'NEWS_UPDATE_SUCCESS'				=>	'Bravo!<br />News modifi&eacute;e avec succ&egrave;s.',
			'NEWS_DELETE_SUCCESS'				=>	'Bravo!<br />News supprim&eacute;e avec succ&egrave;s.',
			'NEWS_PUBLISH_OK'					=>	'Bravo!<br />La news est desormais visible dans le site.',
			'NEWS_HIDE_OK'						=>	'Bravo!<br />La news a &eacute;t&eacute; masqu&eacute;e.',
			'NEWSCAT_CODE_MANDATORY'			=>	'Erreur!<br />Code obligatoire.',
			'NEWSCAT_LABEL_MANDATORY'			=>	'Erreur!<br />Vous devez pr&eacute;ciser un libell&eacute;.',
			'NEWSCAT_EXISTS'					=>	'Erreur!<br />Cette cat&eacute;goie existe d&eacute;j&agrave;.',
			'NEWSCAT_SUCCESS'					=>	'Bravo!<br />Cat&eacute;gorie cr&eacute;&eacute;e avec succ&egrave;.',
			'NEWSCAT_DELETE_SUCCESS'			=>	'Bravo!<br />Categorie suprim&eacute;e avec succes.',
			'NEWSCAT_UPDATE_SUCCESS'			=>	'Bravo!<br />Cat&eacute;gorie modifi&eacute;e avec succ&egrave;s.',
			'NEWSCAT_PUBLISH'					=>	'Bravo!<br />Categorie rendue visible. Toutes les news y relatives seront accessibles.',
			'NEWSCAT_HIDE'						=>	'Bravo!<br />Cat&eacute;gorie rendue invisible. Tous les articles appartenant &agrave; cette cat&eacute;gorie seront inaccessibles au visiteur!',
			'NEWS_AUTHOR_GROUP_EXISTS'			=>	'Erreur!<br />Ce goupe existe d&eacute;j&agrave;.',
			'NEWS_AUTHOR_GROUP_EMPTY'			=>	'Erreur!<br />Vous devez remplir le champ de texte avent de proc&eacute;der.',
			'NEWS_AUTHOR_GROUP_SUCCESS'			=>	'Bravo!<br />Groupe d\'auteurs cr&eacute;&eacute; avec succ&egrave;s.',
			'NEWS_AUTHOR_GROUP_UPDATE_SUCCESS'	=>	'Bravo!<br />Groupe modifi&eacute; avec succ&egrave;s.',
			'NEWS_AUTHOR_GROUP_DELETE_SUCCESS'	=>	'Bravo!<br /Groupe d\'auteurs supprim&eacute; avec succ&egrave;s.',
			'NEWS_AUTHOR_UPDATE_SUCCESS'		=>	'Bravo!<br />Informations sur l\'auteur mises &agrave; jour avec succ&egrave;s.',
			'NEWS_AUTHOR_DELETE_SUCCESS'		=>	'Bravo!<br />Auteur supprim&eacute; avec succ&egrave;s.',
			'NEWS_AUTHOR_SUCCESS'				=>	'Bravo!<br />Auteur ajout&eacute; avec succ&egrave;s.',
			'NEWS_AUTHOR_EXISTS'				=>	'Erreur!<br />Cet auteur a d&eacute;j&agrave; &eacute;t&eacute; enregistr&eacute;.',
			'NEWS_AUTHOR_FIRST_NAME_ERROR'		=>	'Erreur!<br />Vous devez fournir un nom et/ou pr&eacute;nom pour l\'auteur.',
			'NEWS_AUTHOR_SEX_ERROR'				=>	'Erreur!<br />Vous devez choisir un sexe pour l\'auteur.',
			'NEWS_COMMENT_PUBLISH'				=>	'Bravo!<br />Ce commentaire est maintenant visible par les visiteurs du site web.',
			'NEWS_COMMENT_HIDE'					=>	'Bravo!<br />Ce commentaire est rendu invisible pour les visiteurs du site web.',
			'NEWS_COMMENT_DELETE'				=>	'Bravo!<br />Commentaire supprim&eacute; avec succ&egrave;s.',

			//Main page display
			"NEWS_SIDE_BOX_TITLE" 				=> 	"News",
			"NEWS_BOX_TITLE" 					=> 	"News &agrave; la une",
			"NEWS_BOX_LINK"						=> 	"&raquo;Aller aux news",
			"NEWS_BOX_LINK_ALL"					=> 	"Toutes les news",
			"NEWS_PAGE_TITLE"					=> 	"Espace News",
			"NEWS_PAGE_HEADER"					=> 	"R&eacute;gion du Nord-Ouest :: Espace News",
			"NEWS_PAGE_CAT_HEADER"				=> 	"R&eacute;gion du Nord-Ouest :: News par cat&eacute;gories",
			"NEWS_PAGE_BACK"					=> 	"Retour aux news",
			"NEWS_PJ"							=> 	"Pi&eacute;ce-jointe",
			"NEWS_CAT_SIDE_BOX_TITLE"			=>	"News par cat&eacute;gories",
			"NEWS_CAT_ERR"						=>	"Aucune cat&eacute;gorie de news",
			"NEWS_LOCATION"						=>	"Lieu",
			"NO_NEWS"							=>	"Aucun &eacute;v&eacute;nement &agrave; afficher",
			"NEWS_MORE"                         =>  "En savoir plus",
			"NEWS_HOME_TITLE"                   =>  "A la une"
			)
	);