<?php
	$mod_lang_output = array_merge($lang_output,
			array(
			
			//General
			'MODULE_NAME'								=>	'<i class=\'fa fa-quote-left icon_info icon_color\'></i>&nbsp;DailyQuote Manager',
			'MODULE_DESCR'								=>	'Gestionnaire des citations quotidiennes',
			'FORM_BUTTON_UPDATE'						=>	'Mettre &agrave; jour',
			'FORM_HELP_LEAVE_EMPTY'						=>	'Laisser vide si identique',
			'FORM_HELP_CRT_MAX'							=>	'Caract&egrave;res max.',
			'FORM_LABEL_LANGUAGE'						=>	'Langue',
			'FORM_LABEL_SEX'							=>	'Sexe',
			'FORM_VALUE_CHOOSE'							=> 	'Choisir',
			'FORM_VALUE_SEX_1'							=>	'Masculin',
			'FORM_VALUE_SEX_2'							=>	'Feminin',
				
			//Admin --	Tables
			'TABLE_HEADER_TITLE' 						=> 	'Titre',
			'TABLE_HEADER_AUTHOR' 						=> 	'Auteur',
			'TABLE_HEADER_DATE-CREA'					=> 	'Cr&eacute;&eacute; le',
			'TABLE_HEADER_DATE-START'					=> 	'D&eacute;but',
			'TABLE_HEADER_DATE-END'						=> 	'Fin',
			'TABLE_HEADER_ACTION'						=> 	'Actions',
			'TABLE_HEADER_CATEGORY'						=>	'Cat&eacute;gorie',
			'TABLE_HEADER_AUTHOR_GROUP'					=>	'Groupe',
			'TABLE_HEADER_DESCRIPTION'					=>	'Description',
			'TABLE_HEADER_DAILYQUOT_POSITION'			=>	'Position sur la page',
			'TABLE_HEADER_DAILYQUOT_REFERENCE'			=>	'R&eacute;f&eacute;rence',
			'TABLE_HEADER_DAILYQUOT_CONTENT'			=>	'Contenu',
				
			//Admin -- Forms
			'FORM_LABEL_CATEGORY'						=>	'Cat&eacute;gorie',
			'FORM_LABEL_DAILYQUOT_CATEGORY'				=>	'Rubrique',
			'FORM_LABEL_CODE'							=>	'Code',
			'FORM_LABEL_TITLE'							=>	'Titre',
			'FORM_LABEL_DAILYQUOT_POSITION'				=>	'Position sur la page',
			'FORM_LABEL_DAILYQUOT_PAGE'					=>	'Page pour citation',
			'FORM_LABEL_DAILYQUOT_HEADER'				=>	'Chapeau',
			'FORM_LABEL_DAILYQUOT_TAGS'					=>	'Mots-cl&eacute;s',
			'FORM_LABEL_DAILYQUOT_CONTENT'				=>	'Contenu principal',
			'FORM_LABEL_DAILYQUOT_TITLE'				=>	'Titre',
			'FORM_LABEL_LABEL'							=>	'Libell&eacute;',
			'FORM_LABEL_DATE-PUB'						=>	'Date de publication',
			'FORM_LABEL_DATE-CREA'						=>	'Date de cr&eacute;ation',
			'FORM_LABEL_DAILYQUOT_THUMBNAIL'			=>	'Imagette',
			'FORM_LABEL_FIRST-NAME'						=>	'Pr&eacute;nom',
			'FORM_LABEL_LAST-NAME'						=>	'Nom',
			'FORM_LABEL_GROUP'							=>	'Groupe',
			'FORM_LABEL_AUTHOR_GROUP'					=>	'Groupe d\'auteurs',
			'FORM_LABEL_DESCRIPTION'					=>	'Description',
			'FORM_LABEL_DAILYQUOT_IMG_HEADER'			=>	'Image d\'ent&ecirc;te',
			'FORM_LABEL_DAILYQUOT_EXP-DATE'				=>	'Date d\'expiration de la citation',
			'FORM_LABEL_EXP-DATE'						=>	'Date d\'expiration',
			'FORM_LABEL_ADD_DAILYQUOT'					=>	'Ajouter un citation',
			'FORM_BUTTON_ADD_DAILYQUOT'					=>	'Ajouter une citation',
			'FORM_BUTTON_ADD_DAILYQUOT_AUTHOR'			=>	'Ajouter un auteur',
			'FORM_BUTTON_ADD_CATEGORY'					=>	'Ajouter la cat&eacute;gorie',
			'FORM_BUTTON_ADD_AUTHOR_GROUP'				=>	'Ajouter un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_AUTHOR_GROUP'			=>	'Modifier un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_DAILYQUOT'				=>	'Modifier la citation',
				
			//Admin -- Headers
			'PAGE_HEADER_ADD_DAILYQUOT'					=>	'Ajouter une citation',
			'PAGE_HEADER_ADD_DAILYQUOT_CATEGORY'		=>	'Ajouter une cat&eacute;gorie de citation',
			'PAGE_HEADER_ADD_AUTHOR_GROUP'				=>	'Ajouter un groupe d\'auteur',
			'PAGE_HEADER_ADD_DAILYQUOT_AUTHOR'			=>	'Ajouter un auteur',
			'PAGE_HEADER_UPDATE_AUTHORS_GROUP'			=>	'Modifier un groupe d\'auteurs',
			'PAGE_HEADER_UPDATE_DAILYQUOT'				=>	'Modifier la citation',
			'PAGE_HEADER_UPDATE_DAILYQUOT_CATEGORY'		=>	'Modifier une cat&eacute;gorie de citation',
			'PAGE_HEADER_UPDATE_DAILYQUOT_AUTHOR'		=>	'Modifier un auteur',
			'PAGE_HEADER_LIST_DAILYQUOTS'				=>	'Afficher les citations',
			'PAGE_HEADER_LIST_DAILYQUOT_CATEGORIES'		=>	'Afficher les cat&eacute;gories',
			'PAGE_HEADER_LIST_DAILYQUOT_COMMENTS'		=>	'Afficher les commentaires',
			'PAGE_HEADER_LIST_DAILYQUOT_AUTHORS'		=>	'Afficher les auteurs',
			'PAGE_HEADER_LIST_AUTHOR_GROUPS'			=>	'Afficher les groupes d\'auteurs',
			
			'PAGE_LINK_ADD_DAILYQUOT_AUTHOR_GROUP'		=>	'Ajouter un groupe d\'auteur',
			'PAGE_LINK_ADD_DAILYQUOT_AUTHOR'			=>	'Ajouter un auteur',

			//Admin menu
			"DAILYQUOT_ADMIN_MENU_DISPLAY"				=>	"Display quotes",
			"DAILYQUOT_ADMIN_MENU_CREATE"				=>	"Add a quote",
			"DAILYQUOT_ADMIN_MENU_CAT_DISPLAY"			=>	"Show categories",
			"DAILYQUOT_ADMIN_MENU_CAT_CREATE"			=>	"Add category",

			//Admin callouts
			'CALLOUT_INSERT_SUCCESS'					=>	'Hurray!<br />Quote successfuly added.',
			'CALLOUT_INSERT_ERROR'						=>	'Sorry!<br />An error occured while you tried to insert a new quote in our database.',
			'CALLOUT_INSERT_ERROR_EMPTY'				=>	'Sorry!<br />You need to enter a new quote before you proceed.',
			'CALLOUT_INSERT_ERROR_EXIST'				=>	'Sorry!<br />The quote you you have entered exists already in our database!',
			'CALLOUT_INSERT_ERROR_EXIST_SAME_TITLE'		=>	'Sorry!<br />There is already a quote registered with the proposed title!',
			'CALLOUT_INSERT_ERROR_EXIST_SAME_DAY'		=>	'Sorry!<br />There is already a quote registered for the day you have selected!.',
			'CALLOUT_INSERT_ERROR_MANDATORY'			=>	'Sorry!<br />You need to fill <strong>all</strong> mandatory fields please...',
			'CALLOUT_UPDATE_SUCCESS'					=>	'Hurray!<br />Quote successfuly updated.',
			'CALLOUT_UPDATE_ERROR'						=>	'Sorry!<br />An error occured while you tried to update a quote.',
			'CALLOUT_DELETE_SUCCESS'					=>	'Hurray!<br />Announcement successfuly deleted.',
			'CALLOUT_DELETE_ERROR'						=>	'Sorry!<br />An error occured while you tried to delete a quote.',
			'CALLOUT_DELETE_WARNING'					=>	'Do you really want to delete that quote?',
			'CALLOUT_HIDE'								=>	'Hurray.<br />Quote successfuly hidden to the visitors.',
			'CALLOUT_SHOW'								=>	'Hurray.<br />Quote successfuly published.',
			'CALLOUT_CAT_HIDE'							=>	'Hurray.<br />Category of quote has been successfuly hidden.',
			'CALLOUT_CAT_SHOW'							=>	'Hurray.<br />Category of quote has been successfuly published.',
			'CALLOUT_CAT_DELETE_SUCCESS'				=>	'Hurray.<br /Category of quote has been successfuly deleted.',
			'CALLOUT_CAT_DELETE_ERROR'					=>	'Sorry.<br />An error occured while you tried to delete a category of quote.',
			'CALLOUT_CAT_DELETE_WARNING'				=>	'If done, all quotes of same category shall be deleted. Would you like to continue ?',
			'CALLOUT_UPDATE_ERROR_MANDATORY'			=>	'Error!<br />You must fill <strong>all</strong>mandatory fields...',
			'CALLOUT_UPDATE_ERROR_EMPTY'				=>	'Error.<br />You must specify a category...',
			'CALLOUT_UPDATE_ERROR_EXIST'				=>	'Sorry<br />This quote already exists<br/>Please try again...!',
			'CALLOUT_CAT_INSERT_ERROR_EMPTY'			=>	'Error.<br />You must specify a category...',
			'CALLOUT_CAT_INSERT_ERROR_EXIST'			=>	'Sorry!<br />That category already exists.<br />Please try again...!',
			'CALLOUT_CAT_INSERT_SUCCESS'				=>	'Hurray!<br />Category successfully created',

			//Admin actions
			"DAILYQUOT_ACTION_UPDATE"					=>	"Update the quote",
			"DAILYQUOT_ACTION_DELETE"					=>	"Delete the quote",
			"DAILYQUOT_ACTION_SHOW"						=>	"Publish the quote",
			"DAILYQUOT_ACTION_HIDE"						=>	"Hide the quote",
			"DAILYQUOT_CAT_ACTION_UPDATE"				=>	"Update the category",
			"DAILYQUOT_CAT_ACTION_DELETE"				=>	"Delete the category",
			"DAILYQUOT_CAT_ACTION_SHOW"					=>	"Publish the category",
			"DAILYQUOT_CAT_ACTION_HIDE"					=>	"Hide the category",
			
			//Main page display
			"DAILYQUOT_RBOX_TITLE" 						=> 	"Citations",
			"DAILYQUOT_BOX_TITLE" 						=> 	"Citations r&eacute;centes",
			"DAILYQUOT_BOX_LINK"						=> 	"&raquo;Aller &agrave; au babillard",
			"DAILYQUOT_BOX_LINK_ALL"					=> 	"Toutes les citations",
			"DAILYQUOT_PAGE_TITLE"						=> 	"Espace Citations",
			"DAILYQUOT_PAGE_HEADER"						=> 	":: Citations",
			"DAILYQUOT_PAGE_CAT_HEADER"					=> 	":: Citations par cat&eacute;gories",
			"DAILYQUOT_PAGE_BACK"						=> 	"Retour aux citations",
			"DAILYQUOT_PJ"								=> 	"Pi&eacute;ce-jointe",
			"DAILYQUOT_RBOX_CAT_TITLE"					=>	"Citations par cat&eacute;gories",
			"DAILYQUOT_LOCATION"						=>	"Lieu",
			"NO_DAILYQUOT"								=>	"Aucune citation &agrave; afficher",
			"NO_DAILYQUOT_CATEGORY"						=>	"Aucune categorie d\'citation &agrave; afficher",
			
			//Citation
			"DAILYQUOT_RBOX_TITLE" 						=> 	"Les citations",
			"DAILYQUOT_BOX_TITLE" 						=> 	"Les citations",
			"DAILYQUOT_BOX_LINK"						=> 	"&raquo;Toutes les citations",
			"DAILYQUOT_BOX_LINK_ALL"					=> 	"Toutes les citations",
			"DAILYQUOT_PAGE_TITLE"						=> 	"Les citations",
			"DAILYQUOT_PAGE_HEADER"						=> 	":: Les citations",
			"DAILYQUOT_PAGE_CAT_HEADER"					=> 	":: Citations par cat&eacute;gories",
			"DAILYQUOT_PAGE_BACK"						=> 	"&raquo;Retour au babillard",
			"DAILYQUOT_PJ"								=> 	"Pi&eacute;ce-jointe",
			"DAILYQUOT_RBOX_CAT_TITLE"					=>	"Citations par cat&eacute;gories"					
			)
	);