<?php
	$mod_lang_output = array_merge($lang_output,
			array(
			
			//General
			'MODULE_NAME'								=>	'<i class=\'fa fa-quote-left icon_info icon_color\'></i>&nbsp;DailyQuote Manager',
			'MODULE_DESCR'								=>	'Gestionnaire des citations quotidiennes',
			'FORM_BUTTON_UPDATE'						=>	'Mettre &agrave; jour',
			'FORM_HELP_LEAVE_EMPTY'						=>	'Laisser vide si identique',
			'FORM_HELP_CRT_MAX'							=>	'Caract&egrave;res max.',
			'FORM_LABEL_LANGUAGE'						=>	'Langue',
			'FORM_LABEL_SEX'							=>	'Sexe',
			'FORM_VALUE_CHOOSE'							=> 	'Choisir',
			'FORM_VALUE_SEX_1'							=>	'Masculin',
			'FORM_VALUE_SEX_2'							=>	'Feminin',
				
			//Admin --	Tables
			'TABLE_HEADER_TITLE' 						=> 	'Titre',
			'TABLE_HEADER_AUTHOR' 						=> 	'Auteur',
			'TABLE_HEADER_DATE-CREA'					=> 	'Cr&eacute;&eacute; le',
			'TABLE_HEADER_DATE-START'					=> 	'D&eacute;but',
			'TABLE_HEADER_DATE-END'						=> 	'Fin',
			'TABLE_HEADER_ACTION'						=> 	'Actions',
			'TABLE_HEADER_CATEGORY'						=>	'Cat&eacute;gorie',
			'TABLE_HEADER_AUTHOR_GROUP'					=>	'Groupe',
			'TABLE_HEADER_DESCRIPTION'					=>	'Description',
			'TABLE_HEADER_DAILYQUOT_POSITION'			=>	'Position sur la page',
			'TABLE_HEADER_DAILYQUOT_REFERENCE'			=>	'R&eacute;f&eacute;rence',
			'TABLE_HEADER_DAILYQUOT_CONTENT'			=>	'Contenu',
				
			//Admin -- Forms
			'FORM_LABEL_CATEGORY'						=>	'Cat&eacute;gorie',
			'FORM_LABEL_DAILYQUOT_CATEGORY'				=>	'Rubrique',
			'FORM_LABEL_CODE'							=>	'Code',
			'FORM_LABEL_TITLE'							=>	'Titre',
			'FORM_LABEL_DAILYQUOT_POSITION'				=>	'Position sur la page',
			'FORM_LABEL_DAILYQUOT_PAGE'					=>	'Page pour citation',
			'FORM_LABEL_DAILYQUOT_HEADER'				=>	'Chapeau',
			'FORM_LABEL_DAILYQUOT_TAGS'					=>	'Mots-cl&eacute;s',
			'FORM_LABEL_DAILYQUOT_CONTENT'				=>	'Contenu principal',
			'FORM_LABEL_DAILYQUOT_TITLE'				=>	'Titre',
			'FORM_LABEL_LABEL'							=>	'Libell&eacute;',
			'FORM_LABEL_DATE-PUB'						=>	'Date de publication',
			'FORM_LABEL_DATE-CREA'						=>	'Date de cr&eacute;ation',
			'FORM_LABEL_DAILYQUOT_THUMBNAIL'			=>	'Imagette',
			'FORM_LABEL_FIRST-NAME'						=>	'Pr&eacute;nom',
			'FORM_LABEL_LAST-NAME'						=>	'Nom',
			'FORM_LABEL_GROUP'							=>	'Groupe',
			'FORM_LABEL_AUTHOR_GROUP'					=>	'Groupe d\'auteurs',
			'FORM_LABEL_DESCRIPTION'					=>	'Description',
			'FORM_LABEL_DAILYQUOT_IMG_HEADER'			=>	'Image d\'ent&ecirc;te',
			'FORM_LABEL_DAILYQUOT_EXP-DATE'				=>	'Date d\'expiration de la citation',
			'FORM_LABEL_EXP-DATE'						=>	'Date d\'expiration',
			'FORM_LABEL_ADD_DAILYQUOT'					=>	'Ajouter un citation',
			'FORM_BUTTON_ADD_DAILYQUOT'					=>	'Ajouter une citation',
			'FORM_BUTTON_ADD_DAILYQUOT_AUTHOR'			=>	'Ajouter un auteur',
			'FORM_BUTTON_ADD_CATEGORY'					=>	'Ajouter la cat&eacute;gorie',
			'FORM_BUTTON_ADD_AUTHOR_GROUP'				=>	'Ajouter un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_AUTHOR_GROUP'			=>	'Modifier un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_DAILYQUOT'				=>	'Modifier la citation',
				
			//Admin -- Headers
			'PAGE_HEADER_ADD_DAILYQUOT'					=>	'Ajouter une citation',
			'PAGE_HEADER_ADD_DAILYQUOT_CATEGORY'		=>	'Ajouter une cat&eacute;gorie de citation',
			'PAGE_HEADER_ADD_AUTHOR_GROUP'				=>	'Ajouter un groupe d\'auteur',
			'PAGE_HEADER_ADD_DAILYQUOT_AUTHOR'			=>	'Ajouter un auteur',
			'PAGE_HEADER_UPDATE_AUTHORS_GROUP'			=>	'Modifier un groupe d\'auteurs',
			'PAGE_HEADER_UPDATE_DAILYQUOT'				=>	'Modifier la citation',
			'PAGE_HEADER_UPDATE_DAILYQUOT_CATEGORY'		=>	'Modifier une cat&eacute;gorie de citation',
			'PAGE_HEADER_UPDATE_DAILYQUOT_AUTHOR'		=>	'Modifier un auteur',
			'PAGE_HEADER_LIST_DAILYQUOTS'				=>	'Afficher les citations',
			'PAGE_HEADER_LIST_DAILYQUOT_CATEGORIES'		=>	'Afficher les cat&eacute;gories',
			'PAGE_HEADER_LIST_DAILYQUOT_COMMENTS'		=>	'Afficher les commentaires',
			'PAGE_HEADER_LIST_DAILYQUOT_AUTHORS'		=>	'Afficher les auteurs',
			'PAGE_HEADER_LIST_AUTHOR_GROUPS'			=>	'Afficher les groupes d\'auteurs',
			
			'PAGE_LINK_ADD_DAILYQUOT_AUTHOR_GROUP'		=>	'Ajouter un groupe d\'auteur',
			'PAGE_LINK_ADD_DAILYQUOT_AUTHOR'			=>	'Ajouter un auteur',

			//Admin menu
			"DAILYQUOT_ADMIN_MENU_DISPLAY"				=>	"Afficher les citations",
			"DAILYQUOT_ADMIN_MENU_CREATE"				=>	"Ajouter une citation",
			"DAILYQUOT_ADMIN_MENU_CAT_DISPLAY"			=>	"Afficher les cat&eacute;gories",
			"DAILYQUOT_ADMIN_MENU_CAT_CREATE"			=>	"Ajouter une cat&eacute;gorie",

			//Admin callouts
			'CALLOUT_INSERT_SUCCESS'					=>	'Bravo!<br />Citation ajout&eacute;e avec succ&egrave;s.',
			'CALLOUT_INSERT_ERROR'						=>	'D&eacute;sol&eacute;!<br />Une erreur est survenue au cours de l\'insertion d\'une citation.',
			'CALLOUT_INSERT_ERROR_EMPTY'				=>	'D&eacute;sol&eacute;!<br />Vous devez remplir les champs obligatoires (avec *).',
			'CALLOUT_INSERT_ERROR_EXIST'				=>	'D&eacute;sol&eacute;!<br />Cette citation a d&eacute;j&agrave; &eacute;t&eacute; enregistr&eacute;e!',
			'CALLOUT_INSERT_ERROR_EXIST_SAME_TITLE'		=>	'D&eacute;sol&eacute;!<br />Cet intitul&eacute; a d&eacute;j&agrave; &eacute;t&eacute; enregistr&eacute; pour une autre citation!',
			'CALLOUT_INSERT_ERROR_EXIST_SAME_DAY'		=>	'D&eacute;sol&eacute;!<br />Une citation a d&eacute;j&agrave; &eacute;t&eacute; enregistr&eacute;(e) pour le jour s&eacute;lectionn&eacute;!.',
			'CALLOUT_INSERT_ERROR_MANDATORY'			=>	'D&eacute;sol&eacute;!<br />Veuillez remplir <strong>tous</strong> les champs obligatoires svp...',
			'CALLOUT_UPDATE_SUCCESS'					=>	'Bravo!<br />Citation mise &agrave; jour avec succ&egrave;s.',
			'CALLOUT_UPDATE_ERROR'						=>	'D&eacute;sol&eacute;!<br />Une erreur est survenue au cours de la mise &agrave; jour d\'une citation.',
			'CALLOUT_DELETE_SUCCESS'					=>	'Bravo!<br />Citation supprim&eacute;e avec succ&egrave;s',
			'CALLOUT_DELETE_ERROR'						=>	'D&eacute;sol&eacute;!<br />Une erreur est survenue au cours de la suppression d\'une citation',
			'CALLOUT_DELETE_WARNING'					=>	'Attention!<br />&Ecirc;tes-vous s&ucirc;r de vouloir supprimer cette Citation?',
			'CALLOUT_HIDE'								=>	'Bravo.<br />Citation masqu&eacute;e avec succ&egrave;s.',
			'CALLOUT_SHOW'								=>	'Bravo.<br />Citation d&eacute;sormais accessible aux visiteurs du site',
			'CALLOUT_CAT_HIDE'							=>	'Bravo.<br />Cat&eacute;gorie de citation masqu&eacute;e avec succ&egrave;s.',
			'CALLOUT_CAT_SHOW'							=>	'Bravo.<br />Cat&eacute;gorie de citation d&eacute;sormais accessible aux visiteurs du site.',
			'CALLOUT_CAT_DELETE_SUCCESS'				=>	'Bravo.<br />Cat&eacute;gorie de citation supprim&eacute;e avec succ&egrave;s.',
			'CALLOUT_CAT_DELETE_ERROR'					=>	'D&eacute;sol&eacute;.<br />Une erreur est survenue au cours de la suppression d\'une cat&eacute;gorie de citation.',
			'CALLOUT_CAT_DELETE_WARNING'				=>	'Attention!<br/>La suppression de cette cat&eacute;gorie entrainera celle des Citations correspondantes!\nSouhaitez vous continuer ?',
			'CALLOUT_UPDATE_ERROR_MANDATORY'			=>	'Erreur!<br />Veuillez remplir <strong>tous</strong> les champs obligatoires svp...',
			'CALLOUT_UPDATE_ERROR_EMPTY'				=>	'Erreur!<br />Bien vouloir sp&eacute;cifier une cat&eacute;gorie...',
			'CALLOUT_UPDATE_ERROR_EXIST'				=>	'Erreur!Cette citation a d&eacute;j&agrave; &eacute;t&eacute; attribu&eacute;e.<br />Bien vouloir en choisir une autre svp',
			'CALLOUT_CAT_INSERT_ERROR_EMPTY'			=>	'Erreur!<br />Bien vouloir sp&eacute;cifier une cat&eacute;gorie...',
			'CALLOUT_CAT_INSERT_ERROR_EXIST'			=>	'D&eacute;sol&eacute;!<br />Cette cat&eacute;gorie existe d&eacute;j&agrave;.<br />Bien vouloir reessayer...!',
			'CALLOUT_CAT_INSERT_SUCCESS'				=>	'Bravo.<br />Cat&eacute;gorie ajout&eacute;e avec succ&egrave;s',

			//Admin actions
			"DAILYQUOT_ACTION_UPDATE"					=>	"Modifier la citation",
			"DAILYQUOT_ACTION_DELETE"					=>	"Supprimer la citation",
			"DAILYQUOT_ACTION_SHOW"						=>	"Publier la citation",
			"DAILYQUOT_ACTION_HIDE"						=>	"Masquer la citation",
			"DAILYQUOT_CAT_ACTION_UPDATE"				=>	"Modifier la cat&eacute;gorie",
			"DAILYQUOT_CAT_ACTION_DELETE"				=>	"Delete la cat&eacute;gorie",
			"DAILYQUOT_CAT_ACTION_SHOW"					=>	"Publier la cat&eacute;gorie",
			"DAILYQUOT_CAT_ACTION_HIDE"					=>	"Masquer la cat&eacute;gorie",
			
			//Main page display
			"DAILYQUOT_RBOX_TITLE" 						=> 	"Citations",
			"DAILYQUOT_BOX_TITLE" 						=> 	"Citations r&eacute;centes",
			"DAILYQUOT_BOX_LINK"						=> 	"&raquo;Aller &agrave; au babillard",
			"DAILYQUOT_BOX_LINK_ALL"					=> 	"Toutes les citations",
			"DAILYQUOT_PAGE_TITLE"						=> 	"Espace Citations",
			"DAILYQUOT_PAGE_HEADER"						=> 	"CABB :: Babillard",
			"DAILYQUOT_PAGE_CAT_HEADER"					=> 	"CABB :: Citations par cat&eacute;gories",
			"DAILYQUOT_PAGE_BACK"						=> 	"Retour aux citations",
			"DAILYQUOT_PJ"								=> 	"Pi&eacute;ce-jointe",
			"DAILYQUOT_RBOX_CAT_TITLE"					=>	"Citations par cat&eacute;gories",
			"DAILYQUOT_LOCATION"						=>	"Lieu",
			"NO_DAILYQUOT"								=>	"Aucune citation &agrave; afficher",
			"NO_DAILYQUOT_CATEGORY"						=>	"Aucune categorie de citation &agrave; afficher",
			
			//Citation
			"DAILYQUOT_RBOX_TITLE" 						=> 	"Les citations",
			"DAILYQUOT_BOX_TITLE" 						=> 	"Les citations",
			"DAILYQUOT_BOX_LINK"						=> 	"&raquo;Toutes les citations",
			"DAILYQUOT_BOX_LINK_ALL"					=> 	"Toutes les citations",
			"DAILYQUOT_PAGE_TITLE"						=> 	"Les citations",
			"DAILYQUOT_PAGE_HEADER"						=> 	":: Les citations",
			"DAILYQUOT_PAGE_CAT_HEADER"					=> 	":: Citations par cat&eacute;gories",
			"DAILYQUOT_PAGE_BACK"						=> 	"&raquo;Retour au babillard",
			"DAILYQUOT_PJ"								=> 	"Pi&eacute;ce-jointe",
			"DAILYQUOT_RBOX_CAT_TITLE"					=>	"Citations par cat&eacute;gories"					
			)
	);