<?php
	$mod_lang_output = array_merge($lang_output, 
			array(
			
			//General
			'MODULE_NAME'							=>	'<i class=\'fa fa-crosshairs icon_info icon_color\'></i>&nbsp;Exactions Manager',
			'MODULE_DESCR'							=>	'Exactions manager',
			'FORM_BUTTON_UPDATE'					=>	'Update',
			'FORM_HELP_LEAVE_EMPTY'					=>	'Blank if empty',
			'FORM_HELP_CRT_MAX'						=>	'Max crts.',
			'FORM_LABEL_LANGUAGE'					=>	'Language',
			'FORM_LABEL_SEX'						=>	'Sex',
			'FORM_VALUE_CHOOSE'						=> 	'Choose',
			'FORM_VALUE_SEX_1'						=>	'Male',
			'FORM_VALUE_SEX_2'						=>	'Female',
				
			//Admin --	Tables
			'TABLE_HEADER_TITLE' 					=> 	'Title',
			'TABLE_HEADER_AUTHOR' 					=> 	'Author',
			'TABLE_HEADER_DATE-CREA'				=> 	'Date of creation',
			'TABLE_HEADER_DATE-START'				=> 	'Start',
			'TABLE_HEADER_DATE-END'					=> 	'End',
			'TABLE_HEADER_ACTION'					=> 	'Actions',
			'TABLE_HEADER_CATEGORY'					=>	'Category',
			'TABLE_HEADER_AUTHOR_GROUP'				=>	'Group',
			'TABLE_HEADER_DESCRIPTION'				=>	'Description',
			'TABLE_HEADER_EXACTION_TYPE'            =>  'Type',
			'TABLE_HEADER_EXACTION_NATURE'          =>  'Nature',
			'TABLE_HEADER_EXACTION_VICTIM'          =>  'Victims',
			'TABLE_HEADER_EXACTION_DESCR'           =>  'Description',
			'TABLE_HEADER_EXACTION_DATE'            =>  'Date',
			'TABLE_HEADER_EXACTION_PLACE'           => 'Place',
			'TABLE_HEADER_EXACTION_DIVISION'		=>	'Division',
				
			//Admin -- Forms
			'FORM_LABEL_CATEGORY'					=>	'Category',
			'FORM_LABEL_EXACTION_TYPE'			    =>	'Type of exaction',
			'FORM_LABEL_EXACTION_NATURE'            =>  'Nature of exaction',
			'FORM_LABEL_EXACTION_TOWN'              =>  'Place of exaction',
			'FORM_LABEL_EXACTION_VICTIM'            =>  'Victim(s)',
			'FORM_LABEL_EXACTION_DESCR'             =>  'Circumstances(description)',
			'FORM_LABEL_CODE'						=>	'Code',
			'FORM_LABEL_TITLE'						=>	'Title',
			'FORM_LABEL_EXACTION_AUTHOR'			=>	'Author',
			'FORM_LABEL_HEADER'						=>	'Header',
			'FORM_LABEL_EXACTION_HEADER'			=>	'Short description',
			'FORM_LABEL_EXACTION_TAGS'				=>	'Key words',
			'FORM_LABEL_EXACTION_CONTENT'			=>	'Main content',
			'FORM_LABEL_EXACTION_TITLE'				=>	'Title',
			'FORM_LABEL_LABEL'						=>	'Label',
			'FORM_LABEL_DATE-PUB'					=>	'Date of publication',
			'FORM_LABEL_DATE-CREA'					=>	'Date of creation',
			'FORM_LABEL_EXACTION_THUMBNAIL'			=>	'Thunbnail',
			'FORM_LABEL_FIRST-NAME'					=>	'First name',
			'FORM_LABEL_LAST-NAME'					=>	'Last name',
			'FORM_LABEL_GROUP'						=>	'Group',
			'FORM_LABEL_AUTHOR_GROUP'				=>	'Author group',
			'FORM_LABEL_DESCRIPTION'				=>	'Description',
			'FORM_LABEL_EXACTION_IMG_HEADER'		=>	'Head image',
			'FORM_LABEL_EXACTION_FILE_IMPORT'       =>  'Import exactions data',
			'FORM_LABEL_ADD_EXACTION'				=>	'Insert exaction',
			'FORM_LABEL_ADD_EXACTION_PJ'		    =>	'Add attachment',
			'FORM_LABEL_EXACTION_PJ'                =>  'Attachment',
			'FORM_LABEL_EXACTION_PJ_TITLE'          =>  'Name',
			'FORM_LABEL_EXACTION_PJ_DESCR'          =>  'Description',			
			'FORM_LABEL_EXACTION_DATE'				=>	'Date of exaction',
			'FORM_LABEL_ADD_EXACTION'				=>	'Add a exaction',
			'FORM_BUTTON_ADD_EXACTION'				=>	'Insert exaction',
			'FORM_BUTTON_ADD_EXACTION_PJ'		    =>	'Insert an attachment',
			'FORM_BUTTON_ADD_EXACTION_AUTHOR'		=>	'Insert author',
			'FORM_BUTTON_ADD_CATEGORY'				=>	'Insert category',
			'FORM_BUTTON_ADD_AUTHOR_GROUP'			=>	'Insert group',
			'FORM_BUTTON_UPDATE_AUTHOR_GROUP'		=>	'Update group',
			'FORM_BUTTON_UPDATE_EXACTION'			=>	'Update exaction',
			'FORM_BUTTON_IMPORT_EXACTION'           =>  'Import exactions',					
				
			//Admin -- Headers
			'PAGE_HEADER_ADD_EXACTION'				=>	'New exaction',
			'PAGE_HEADER_ADD_EXACTION_PJ'			=>	'New attachment',
			'PAGE_HEADER_ADD_EXACTION_CATEGORY'		=>	'New category',
			'PAGE_HEADER_ADD_AUTHOR_GROUP'			=>	'New group',
			'PAGE_HEADER_ADD_EXACTION_AUTHOR'		=>	'New author',
			'PAGE_HEADER_UPDATE_AUTHORS_GROUP'		=>	'Update group',
			'PAGE_HEADER_UPDATE_EXACTION'			=>	'Update exaction',
			'PAGE_HEADER_UPDATE_EXACTION_CATEGORY'	=>	'Update category',
			'PAGE_HEADER_UPDATE_EXACTION_AUTHOR'	=>	'Update author',
			'PAGE_HEADER_LIST_EXACTION'				=>	'Display exactions',
			'PAGE_HEADER_LIST_EXACTION_CATEGORIES'	=>	'Display categories',
			'PAGE_HEADER_LIST_EXACTION_COMMENTS'	=>	'Show comments',
			'PAGE_HEADER_LIST_EXACTION_AUTHORS'		=>	'Display authors',
			'PAGE_HEADER_LIST_AUTHOR_GROUPS'		=>	'Display groups',
			'PAGE_HEADER_EXACTION_IMPORT'           =>  'Import exactions file',
			'PAGE_HEADER_REPORTED_EXACTION_STATS'   =>  'Reported exactions in the NWR',
			'PAGE_HEADER_REPORTED_EXACTION_STATS_TOWNS'   =>  'Exactions per areas',
			
			//Admin -- Forms validations
			'EXACTION_INSERT_ERROR_EMPTY'           =>   'Error!<br />Please fill all mandatory(*) fields.',
			'EXACTION_INSERT_ERROR_EXISTS'          =>   'Error!<br />This exaction has been recorded already.',
			'EXACTION_INSERT_OK'                    =>   'Congratulations!<br />You have successfuly registered a new exaction in the database.',
			'EXACTION_UPDATE_ERROR_EMPTY'           =>   'Error!<br />Please fill all mandatory(*) fields.',
			'EXACTION_UPDATE_OK'                    =>   'Congratulations!<br />You have successfuly updated an exaction entry in the database.',
			'EXACTION_PJ_INSERT_ERROR_EMPTY'        =>   'Error!<br />You must choose a file as an attachment.',
			'EXACTION_PJ_INSERT_ERROR_EXISTS'       =>   'Error<br />This attachment is already registered!',
			'EXACTION_PJ_INSERT_ERROR_TITLE'        =>   'Error!<br />You must provide a title for the file.',
			'EXACTION_PJ_INSERT_ERROR_TYPE'         =>   'Error!<br />This file type is not allowed.',
			'EXACTION_PJ_INSERT_OK'                 =>   'Congratulations!<br />You successfuly attached a document to an exaction record.',

			//Admin menu
			"DB_ADMIN_MENU"							=>	"NWR Database(NOWEDAB)",
			"BD_ADMIN_MENU_NOSO_CRISIS"				=>	"NOSO Crisis",
			"BD_ADMIN_MENU_NOSO_EXACTIONS"			=>	"Exactions",
			"BD_ADMIN_MENU_NOSO_DOCUMENTATION"		=>	"Documentation",
			"BD_ADMIN_MENU_NOSO_EXACTIONS_DISPLAY"	=>	"Display exactions",
			"BD_ADMIN_MENU_NOSO_EXACTIONS_CREATE"	=>	"Add an exaction",
			"BD_ADMIN_MENU_NOSO_EXACTIONS_UPDATE"	=>	"Update exactions",
			"BD_ADMIN_MENU_NOSO_EXACTIONS_DELETE"	=>	"Delete exactions",
			"BD_ADMIN_MENU_STAFF_MINAT"				=>	"Staff MINAT",
			"BD_ADMIN_MENU_DIRECTORY"				=>	"Directory",
			"BD_ADMIN_MENU_SETTINGS"				=>	"DB Settings",
			"BD_ADMIN_MENU_SETTINGS_DATALOAD"		=>	"NOWEDAB - Load data",
			"BD_ADMIN_MENU_SETTINGS_DATAFLUSH"		=>	"NOWEDAB - Flush data",
						
			//Main page display
			"EXACTION_SIDE_BOX_TITLE" 				=> 	"Exactions",
			"EXACTION_BOX_LINK"						=> 	"View all exactions",
			"EXACTION_BOX_LINK_ALL"					=> 	"See all exactions",
			"EXACTION_PAGE_TITLE"					=> 	"Exactions area",
			"EXACTION_PAGE_HEADER"					=> 	"North-West Region :: Exaction board",
			"EXACTION_PAGE_CAT_HEADER"				=> 	"North-West Region :: Exactions by category",
			"EXACTION_PAGE_BACK"					=> 	"Back to exactions",
			"EXACTION_PJ"							=> 	"Attachment",
			"EXACTION_RBOX_CAT_TITLE"				=>	"Categories",
			"EXACTION_LOCATION"						=>	"Place",
			"NO_EXACTION"							=>	"No exaction to be displayed",
			"NO_EXACTION_CATEGORY"					=>	"No category to be displayed",
			"EXACTION_SEARCH_MSG_ERROR"				=>	"Sorry.<br />There's no result matching your search",
			
			//Exaction
			"EXACTION_SIDE_BOX_TITLE" 				=>  "Our exaction board",
			"EXACTION_BOX_TITLE" 					=> 	"Top exactions",
			"EXACTION_BOX_LINK"						=> 	"&raquo;All the exactions",
			"EXACTION_BOX_LINK_ALL"					=> 	"See all the exactions",
			"EXACTION_PAGE_TITLE"					=> 	"Exaction Board of the North-West Region",
			"EXACTION_PAGE_HEADER"					=> 	"NWR :: The exaction board",
			"EXACTION_PAGE_CAT_HEADER"				=> 	"NWR :: Exactions by category ",
			"EXACTION_PAGE_BACK"					=> 	"&raquo;Back to the exaction board",
			"EXACTION_PJ"							=> 	"Attachment",
			'EXACTION_CAT_SIDE_BOX_TITLE'			=>	'Exactions by category',
			'EXACTIONS_DUMP_SUCCESS'                =>  'Exactions dumped successfuly',
			
			//Stats
			'EXACTION_STATS_KILLINGS_LABEL'         =>  'Killings',
			'EXACTION_STATS_ABDUCTIONS_LABEL'       =>  'Abductions',
			'EXACTION_STATS_INJURIES_LABEL'         =>  'Injuries',
			'EXACTION_STATS_BURNINGS_LABEL'         =>  'Burnings and vandalism',
			'EXACTION_STATS_RAPES_LABEL'            =>  'Rapes',
			'EXACTION_STATS_EXTORTIONS_LABEL'       =>  'Extortions and intimidations',
			'EXACTION_STATS_TOTAL_LABEL'            =>  'Total',
			'EXACTION_STATS_HEADER'                 =>  'Reported exactions in the North-West Region',
			'EXACTION_STATS_TOWN_HEADER'            =>  'Total exactions per town',
			
			//Graph title
			'EXACTION_GRAPH_TITLE'                  =>   'Global view of exactions as recorded in the Region'
		)
	);