<?php
	$mod_lang_output = array_merge($lang_output, 
			array(
			
			//General
			'MODULE_NAME'							=>	'<i class=\'fa fa-crosshairs icon_info icon_color\'></i>&nbsp;Exactions Manager',
			'MODULE_DESCR'							=>	'Gestionnaire des exactions',
			'FORM_BUTTON_UPDATE'					=>	'Mettre &agrave; jour',
			'FORM_HELP_LEAVE_EMPTY'					=>	'Laisser vide si identique',
			'FORM_HELP_CRT_MAX'						=>	'Caract&egrave;res max.',
			'FORM_LABEL_LANGUAGE'					=>	'Langue',
			'FORM_LABEL_SEX'						=>	'Sexe',
			'FORM_VALUE_CHOOSE'						=> 	'Choisir',
			'FORM_VALUE_SEX_1'						=>	'Masculin',
			'FORM_VALUE_SEX_2'						=>	'Feminin',
				
			//Admin --	Tables
			'TABLE_HEADER_TITLE' 					=> 	'Titre',
			'TABLE_HEADER_AUTHOR' 					=> 	'Auteur',
			'TABLE_HEADER_DATE-CREA'				=> 	'Cr&eacute;&eacute; le',
			'TABLE_HEADER_DATE-START'				=> 	'D&eacute;but',
			'TABLE_HEADER_DATE-END'					=> 	'Fin',
			'TABLE_HEADER_ACTION'					=> 	'Actions',
			'TABLE_HEADER_CATEGORY'					=>	'Cat&eacute;gorie',
			'TABLE_HEADER_AUTHOR_GROUP'				=>	'Groupe',
			'TABLE_HEADER_DESCRIPTION'				=>	'Description',
			'TABLE_HEADER_EXACTION_TYPE'            =>  'Type',
			'TABLE_HEADER_EXACTION_NATURE'          =>  'Nature',
			'TABLE_HEADER_EXACTION_VICTIM'          =>  'Victimes',
			'TABLE_HEADER_EXACTION_DESCR'           =>  'Description',
			'TABLE_HEADER_EXACTION_DATE'            =>  'Date',
			'TABLE_HEADER_EXACTION_PLACE'           =>  'Lieu',
			'TABLE_HEADER_EXACTION_DIVISION'		=>	'D&eacute;partement',
				
			//Admin -- Forms
			'FORM_LABEL_CATEGORY'					=>	'Cat&eacute;gorie',
			'FORM_LABEL_EXACTION_TYPE'			    =>	'Type d\'exaction',
			'FORM_LABEL_EXACTION_NATURE'            =>  'Nature de l\'exaction',
			'FORM_LABEL_EXACTION_TOWN'              =>  'Lieu',
			'FORM_LABEL_EXACTION_VICTIM'            =>  'Victime(s)',
			'FORM_LABEL_EXACTION_DESCR'             =>  'Circonstances(description)',
			'FORM_LABEL_CODE'						=>	'Code',
			'FORM_LABEL_TITLE'						=>	'Titre',
			'FORM_LABEL_EXACTION_AUTHOR'		    =>	'Auteur',
			'FORM_LABEL_HEADER'						=>	'Chapeau',
			'FORM_LABEL_EXACTION_HEADER'			=>	'Chapeau',
			'FORM_LABEL_EXACTION_TAGS'				=>	'Mots-cl&eacute;s',
			'FORM_LABEL_EXACTION_CONTENT'			=>	'Contenu principal',
			'FORM_LABEL_EXACTION_TITLE'				=>	'Titre',
			'FORM_LABEL_LABEL'						=>	'Libell&eacute;',
			'FORM_LABEL_DATE-PUB'					=>	'Date de publication',
			'FORM_LABEL_DATE-CREA'					=>	'Date de cr&eacute;ation',
			'FORM_LABEL_EXACTION_THUMBNAIL'			=>	'Imagette',
			'FORM_LABEL_FIRST-NAME'					=>	'Pr&eacute;nom',
			'FORM_LABEL_LAST-NAME'					=>	'Nom',
			'FORM_LABEL_GROUP'						=>	'Groupe',
			'FORM_LABEL_AUTHOR_GROUP'				=>	'Groupe d\'auteurs',
			'FORM_LABEL_DESCRIPTION'				=>	'Description',
			'FORM_LABEL_EXACTION_IMG_HEADER'		=>	'Image d\'ent&ecirc;te',
			'FORM_LABEL_ADD_EXACTION'				=>	'Ajouter un exaction',
			'FORM_LABEL_ADD_EXACTION_PJ'		    =>	'Ajouter une pi&egrave;ce-jointe',
			'FORM_LABEL_EXACTION_FILE_IMPORT'       =>  'Importer les donn&eacute;es sur les exactions',
			'FORM_LABEL_EXACTION_PJ'                =>  'Pi&egrave;ce-jointe',
			'FORM_LABEL_EXACTION_PJ_TITLE'          =>  'Titre',
			'FORM_LABEL_EXACTION_PJ_DESCR'          =>  'Description',
			'FORM_LABEL_EXACTION_DATE'				=>	'Date de l\'exaction',
			'FORM_LABEL_ADD_EXACTION'				=>	'Ajouter une exaction',
			'FORM_BUTTON_ADD_EXACTION'				=>	'Ajouter une exaction',
			'FORM_BUTTON_ADD_EXACTION_PJ'			=>	'Ajouter une pi&egrave;ce-jointe',
			'FORM_BUTTON_ADD_EXACTION_AUTHOR'		=>	'Ajouter un auteur',
			'FORM_BUTTON_ADD_CATEGORY'				=>	'Ajouter la cat&eacute;gorie',
			'FORM_BUTTON_ADD_AUTHOR_GROUP'			=>	'Ajouter un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_AUTHOR_GROUP'		=>	'Modifier un groupe d\'auteurs',
			'FORM_BUTTON_UPDATE_EXACTION'			=>	'Modifier l\'exaction',
			'FORM_BUTTON_IMPORT_EXACTION'           =>  'Importer',
				
			//Admin -- Headers
			'PAGE_HEADER_ADD_EXACTION'				=>	'Ajouter une exaction',
			'PAGE_HEADER_ADD_EXACTION_PJ'			=>	'Ajouter une pi&egrave;ce-jointe',
			'PAGE_HEADER_ADD_EXACTION_CATEGORY'		=>	'Ajouter une cat&eacute;gorie d\'exaction',
			'PAGE_HEADER_ADD_AUTHOR_GROUP'			=>	'Ajouter un groupe d\'auteur',
			'PAGE_HEADER_ADD_EXACTION_AUTHOR'		=>	'Ajouter un auteur',
			'PAGE_HEADER_UPDATE_AUTHORS_GROUP'		=>	'Modifier un groupe d\'auteurs',
			'PAGE_HEADER_UPDATE_EXACTION'			=>	'Modifier l\'exaction',
			'PAGE_HEADER_UPDATE_EXACTION_CATEGORY'	=>	'Modifier une cat&eacute;gorie d\'exaction',
			'PAGE_HEADER_UPDATE_EXACTION_AUTHOR'	=>	'Modifier un auteur',
			'PAGE_HEADER_LIST_EXACTION'				=>	'Afficher les exactions',
			'PAGE_HEADER_LIST_EXACTION_CATEGORIES'	=>	'Afficher les cat&eacute;gories',
			'PAGE_HEADER_LIST_EXACTION_COMMENTS'		=>	'Afficher les commentaires',
			'PAGE_HEADER_LIST_EXACTION_AUTHORS'		=>	'Afficher les auteurs',
			'PAGE_HEADER_LIST_AUTHOR_GROUPS'		=>	'Afficher les groupes d\'auteurs',
			'PAGE_HEADER_EXACTION_IMPORT'           =>  'Importer le fichier des exactions',			
			'PAGE_HEADER_REPORTED_EXACTION_STATS'  	=>  'Exactions enregistr&eacute;es dans la R&eacute;gion',
			'PAGE_HEADER_REPORTED_EXACTION_STATS_TOWNS'  	=>  'Statistiques des exactions par localit&eacute;',
			
			//Admin -- Forms validations
			'EXACTION_INSERT_ERROR_EMPTY'           =>   'Erreur!<br />Veuillez remplir tous les champs obligatoires(*) svp',
			'EXACTION_INSERT_ERROR_EXISTS'          =>   'Erreur!<br />Cette exaction a d&eacute;j&agrave; &eacute;t&eacute; enregistr&eacute;e',
			'EXACTION_INSERT_OK'                    =>   'Bravo!<br />Exaction enregistr&eacute;e avec succ&egrave;s dans la base de donn&eacute;es',
			'EXACTION_UPDATE_ERROR_EMPTY'           =>   'Erreur!<br />Veuillez remplir tous les champs obligatoires svp.',
			'EXACTION_UPDATE_OK'                    =>   'Bravo!<br />Donn&eacute;e sur l\'exaction mise &agrave; jour avec succ&egrave;s dans la base de donn&eacute;es',
			'EXACTION_PJ_INSERT_ERROR_EMPTY'        =>   'Erreur<br />Bien vouloir choisir un fichier avant de continuer svp.',
			'EXACTION_PJ_INSERT_ERROR_EXISTS'       =>   'Erreur<br />Pi&egrave;ce-jointe d&eacute;j&agrave; enregistr&eacute;e.',
			'EXACTION_PJ_INSERT_ERROR_TITLE'        =>   'Erreur<br />Vous devez donner un intitul&eacute; &agrave; votre fichier.',
			'EXACTION_PJ_INSERT_ERROR_TYPE'         =>   'Erreur<br />Le type de document choisi n\'est pas autoris&eacute;.',
			'EXACTION_PJ_INSERT_OK'                 =>   'Bravo<br />Pi&egrave;ce-jointe ajout&eacute;e avec succ&egrave;s.',

			//Admin menu
			"DB_ADMIN_MENU"							=>	"Base de Donn&eacute;es RNO",
			"BD_ADMIN_MENU_NOSO_CRISIS"				=>	"Crise anglophone",
			"BD_ADMIN_MENU_NOSO_EXACTIONS"			=>	"Exactions",
			"BD_ADMIN_MENU_NOSO_DOCUMENTATION"		=>	"Documentation",
			"BD_ADMIN_MENU_NOSO_EXACTIONS_DISPLAY"	=>	"Afficher les exactions",
			"BD_ADMIN_MENU_NOSO_EXACTIONS_CREATE"	=>	"Ajouter une exaction",
			"BD_ADMIN_MENU_NOSO_EXACTIONS_UPDATE"	=>	"Modifier les exactions",
			"BD_ADMIN_MENU_NOSO_EXACTIONS_DELETE"	=>	"Supprimer les exactions",
			"BD_ADMIN_MENU_STAFF_MINAT"				=>	"Staff MINAT",
			"BD_ADMIN_MENU_DIRECTORY"				=>	"Repertoire",
			"BD_ADMIN_MENU_SETTINGS"				=>	"Reglages BDD",
			"BD_ADMIN_MENU_SETTINGS_DATALOAD"		=>	"Charger les donn&eacute;es",
			"BD_ADMIN_MENU_SETTINGS_DATAFLUSH"		=>	"Purger les donn&eacute;es",
			
			//Main page display
			"EXACTION_SIDE_BOX_TITLE" 				=> 	"Exactions",
			"EXACTION_BOX_LINK"						=> 	"&raquo;Aller &agrave; au babillard",
			"EXACTION_BOX_LINK_ALL"					=> 	"Toutes les exactions",
			"EXACTION_PAGE_TITLE"					=> 	"Espace Exactions",
			"EXACTION_PAGE_HEADER"					=> 	"NWR :: Babillard",
			"EXACTION_PAGE_CAT_HEADER"				=> 	"NWR :: Exactions par cat&eacute;gories",
			"EXACTION_PAGE_BACK"					=> 	"Retour aux exactions",
			"EXACTION_PJ"							=> 	"Pi&eacute;ce-jointe",
			"EXACTION_RBOX_CAT_TITLE"				=>	"Exactions par cat&eacute;gories",
			"EXACTION_LOCATION"						=>	"Lieu",
			"NO_EXACTION"							=>	"Aucune exaction &agrave; afficher",
			"NO_EXACTION_CATEGORY"					=>	"Aucune categorie d'exaction &agrave; afficher",
			"EXACTION_SEARCH_MSG_ERROR"				=>	"D&eacute;sol&eacute;.<br />Nous n'avons trouv&eacute; aucun resultat correspondant &agrave; votre recherche",
			
			//Exaction
			"EXACTION_SIDE_BOX_TITLE" 				=> 	"Le babillard du CABB",
			"EXACTION_BOX_TITLE" 					=> 	"La une du babillard",
			"EXACTION_BOX_LINK"						=> 	"&raquo;Toutes les exactions",
			"EXACTION_BOX_LINK_ALL"					=> 	"Toutes les exactions",
			"EXACTION_PAGE_TITLE"					=> 	"Le babillard du CABB",
			"EXACTION_PAGE_HEADER"					=> 	"NWR :: Le babillard",
			"EXACTION_PAGE_CAT_HEADER"				=> 	"NWR :: Exactions et communiqu&eacute;s par cat&eacute;gories",
			"EXACTION_PAGE_BACK"					=> 	"&raquo;Retour au babillard",
			"EXACTION_PJ"							=> 	"Pi&eacute;ce-jointe",
			'EXACTION_CAT_SIDE_BOX_TITLE'			=>	'Exactions par cat&eacute;gories',
			'EXACTIONS_DUMP_SUCCESS'                =>  'Importation des exactions r&eacute;ussie',
			
			//Stats
			'EXACTION_STATS_KILLINGS_LABEL'         =>  'Assassinats',
			'EXACTION_STATS_ABDUCTIONS_LABEL'       =>  'Kidnappings',
			'EXACTION_STATS_INJURIES_LABEL'         =>  'Blessures',
			'EXACTION_STATS_BURNINGS_LABEL'         =>  'Incendies et vandalisme',
			'EXACTION_STATS_RAPES_LABEL'            =>  'Viols',
			'EXACTION_STATS_EXTORTIONS_LABEL'       =>  'Extorsions et intimidations',
			'EXACTION_STATS_TOTAL_LABEL'            =>   'Total',
			'EXACTION_STATS_HEADER'                 =>  'Exactions enregistr&eacute;es depuis le debut de la crise',
			'EXACTION_STATS_TOWN_HEADER'            =>  'Exactions par localit&eacute;',
			    
			//Graph title
			'EXACTION_GRAPH_TITLE'                  =>   'Vue globale des exactions enregistr&eacute;es dans le secteur'
		)
	);